apiVersion: apps/v1
kind: Deployment
metadata:
  name: umrs-notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: umrs-notification
  template:
    metadata:
      labels:
        app: umrs-notification
    spec:
      containers:
      - name: umrs-notification
        image: gidyon/umrs-notification:v0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 443
          name: https
          protocol: TCP
        env:
        - name: SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: smtp-creds
              key: port
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: smtp-creds
              key: host
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: smtp-creds
              key: username
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smtp-creds
              key: password
        volumeMounts:
          - name: app-tls
            mountPath: /app/secrets/keys/
            readOnly: true
          - name: app-config
            mountPath: /app/configs/
          - name: mysql-creds-staging
            mountPath: /app/secrets/mysql/
            readOnly: true
      volumes:
      - name: app-tls
        secret:
          secretName: notification-tls-v1
      - name: mysql-creds-staging
        secret:
          secretName: mysql-creds-staging
      - name: app-config
        configMap:
          name: notification-config

---

apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "umrs-notification-hpa"
  namespace: "default"
  labels:
    app: "umrs-notification"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "umrs-notification"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80

---

apiVersion: v1
kind: Service
metadata:
  name: umrs-notification
  labels:
    app: umrs-notification
spec:
  clusterIP: None
  selector:
    app: umrs-notification
  ports:
  - port: 443
    name: https
    targetPort: https
    protocol: TCP
  - port: 80
    name: http
    targetPort: https
    protocol: TCP
