serviceVersion: v1/beta
serviceName: umrs_employment
servicePort: 443
logging:
  level: 1
  timeFormat: 2006-01-02T15:04:05Z07:00
  disabled: true
security:
  tlsCert: /app/secrets/keys/cert
  tlsKey: /app/secrets/keys/key
  serverName: employments.umrs.net
databases:
  sqlDatabase:
    required: true
    address: umrs-mysql:80
    host: umrs-mysql
    port: 80
    userFile: /app/secrets/mysql/username
    passwordFile: /app/secrets/mysql/password
    schemaFile: /app/secrets/mysql/schema
    metadata:
      name: mysql
      dialect: mysql
      orm: gorm
  redisDatabase:
    required: false