apiVersion: v1
kind: Service
metadata:
  name: umrs-employment
  labels:
    app: umrs-employment
spec:
 clusterIP: None
 selector:
  app: umrs-employment
 ports:
  - port: 443
    name: https
    targetPort: https
    protocol: TCP
  - port: 80
    name: http
    targetPort: https
    protocol: TCP
