// Code generated by protoc-gen-go. DO NOT EDIT.
// source: permission.proto

package permission

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// RequestPermissionMethod is the different ways of requesting for permission token
type RequestPermissionMethod int32

const (
	RequestPermissionMethod_UNKNOWN     RequestPermissionMethod = 0
	RequestPermissionMethod_EMAIL       RequestPermissionMethod = 1
	RequestPermissionMethod_SMS         RequestPermissionMethod = 2
	RequestPermissionMethod_USSD        RequestPermissionMethod = 3
	RequestPermissionMethod_FINGERPRINT RequestPermissionMethod = 4
	RequestPermissionMethod_VOICE       RequestPermissionMethod = 5
	RequestPermissionMethod_FACIAL      RequestPermissionMethod = 6
)

var RequestPermissionMethod_name = map[int32]string{
	0: "UNKNOWN",
	1: "EMAIL",
	2: "SMS",
	3: "USSD",
	4: "FINGERPRINT",
	5: "VOICE",
	6: "FACIAL",
}

var RequestPermissionMethod_value = map[string]int32{
	"UNKNOWN":     0,
	"EMAIL":       1,
	"SMS":         2,
	"USSD":        3,
	"FINGERPRINT": 4,
	"VOICE":       5,
	"FACIAL":      6,
}

func (x RequestPermissionMethod) String() string {
	return proto.EnumName(RequestPermissionMethod_name, int32(x))
}

func (RequestPermissionMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{0}
}

// BasicProfile contains basic profile information of the requester
type BasicProfile struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	ProfileThumbUrl      string   `protobuf:"bytes,3,opt,name=profile_thumb_url,json=profileThumbUrl,proto3" json:"profile_thumb_url,omitempty"`
	RoleAtOrganization   string   `protobuf:"bytes,4,opt,name=role_at_organization,json=roleAtOrganization,proto3" json:"role_at_organization,omitempty"`
	OrganizationName     string   `protobuf:"bytes,5,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	OrganizationId       string   `protobuf:"bytes,6,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	WorkEmail            string   `protobuf:"bytes,7,opt,name=work_email,json=workEmail,proto3" json:"work_email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BasicProfile) Reset()         { *m = BasicProfile{} }
func (m *BasicProfile) String() string { return proto.CompactTextString(m) }
func (*BasicProfile) ProtoMessage()    {}
func (*BasicProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{0}
}

func (m *BasicProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicProfile.Unmarshal(m, b)
}
func (m *BasicProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicProfile.Marshal(b, m, deterministic)
}
func (m *BasicProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicProfile.Merge(m, src)
}
func (m *BasicProfile) XXX_Size() int {
	return xxx_messageInfo_BasicProfile.Size(m)
}
func (m *BasicProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicProfile.DiscardUnknown(m)
}

var xxx_messageInfo_BasicProfile proto.InternalMessageInfo

func (m *BasicProfile) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *BasicProfile) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *BasicProfile) GetProfileThumbUrl() string {
	if m != nil {
		return m.ProfileThumbUrl
	}
	return ""
}

func (m *BasicProfile) GetRoleAtOrganization() string {
	if m != nil {
		return m.RoleAtOrganization
	}
	return ""
}

func (m *BasicProfile) GetOrganizationName() string {
	if m != nil {
		return m.OrganizationName
	}
	return ""
}

func (m *BasicProfile) GetOrganizationId() string {
	if m != nil {
		return m.OrganizationId
	}
	return ""
}

func (m *BasicProfile) GetWorkEmail() string {
	if m != nil {
		return m.WorkEmail
	}
	return ""
}

// PermissionMethod is payload for method used to request permission
type PermissionMethod struct {
	Method               RequestPermissionMethod `protobuf:"varint,1,opt,name=method,proto3,enum=umrs.permission.RequestPermissionMethod" json:"method,omitempty"`
	Payload              string                  `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata             map[string]string       `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *PermissionMethod) Reset()         { *m = PermissionMethod{} }
func (m *PermissionMethod) String() string { return proto.CompactTextString(m) }
func (*PermissionMethod) ProtoMessage()    {}
func (*PermissionMethod) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{1}
}

func (m *PermissionMethod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionMethod.Unmarshal(m, b)
}
func (m *PermissionMethod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionMethod.Marshal(b, m, deterministic)
}
func (m *PermissionMethod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionMethod.Merge(m, src)
}
func (m *PermissionMethod) XXX_Size() int {
	return xxx_messageInfo_PermissionMethod.Size(m)
}
func (m *PermissionMethod) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionMethod.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionMethod proto.InternalMessageInfo

func (m *PermissionMethod) GetMethod() RequestPermissionMethod {
	if m != nil {
		return m.Method
	}
	return RequestPermissionMethod_UNKNOWN
}

func (m *PermissionMethod) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *PermissionMethod) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// Actor performs or is affected by an action
type Actor struct {
	Group                int32    `protobuf:"varint,1,opt,name=group,proto3" json:"group,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	FullName             string   `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Actor) Reset()         { *m = Actor{} }
func (m *Actor) String() string { return proto.CompactTextString(m) }
func (*Actor) ProtoMessage()    {}
func (*Actor) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{2}
}

func (m *Actor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Actor.Unmarshal(m, b)
}
func (m *Actor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Actor.Marshal(b, m, deterministic)
}
func (m *Actor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Actor.Merge(m, src)
}
func (m *Actor) XXX_Size() int {
	return xxx_messageInfo_Actor.Size(m)
}
func (m *Actor) XXX_DiscardUnknown() {
	xxx_messageInfo_Actor.DiscardUnknown(m)
}

var xxx_messageInfo_Actor proto.InternalMessageInfo

func (m *Actor) GetGroup() int32 {
	if m != nil {
		return m.Group
	}
	return 0
}

func (m *Actor) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Actor) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

// RequestPermissionTokenRequest is request message to get permission token
type RequestPermissionTokenRequest struct {
	RequesterProfile     *BasicProfile     `protobuf:"bytes,1,opt,name=requester_profile,json=requesterProfile,proto3" json:"requester_profile,omitempty"`
	PermissionMethod     *PermissionMethod `protobuf:"bytes,2,opt,name=permission_method,json=permissionMethod,proto3" json:"permission_method,omitempty"`
	Requester            *Actor            `protobuf:"bytes,3,opt,name=requester,proto3" json:"requester,omitempty"`
	Patient              *Actor            `protobuf:"bytes,4,opt,name=patient,proto3" json:"patient,omitempty"`
	Reason               string            `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RequestPermissionTokenRequest) Reset()         { *m = RequestPermissionTokenRequest{} }
func (m *RequestPermissionTokenRequest) String() string { return proto.CompactTextString(m) }
func (*RequestPermissionTokenRequest) ProtoMessage()    {}
func (*RequestPermissionTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{3}
}

func (m *RequestPermissionTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestPermissionTokenRequest.Unmarshal(m, b)
}
func (m *RequestPermissionTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestPermissionTokenRequest.Marshal(b, m, deterministic)
}
func (m *RequestPermissionTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestPermissionTokenRequest.Merge(m, src)
}
func (m *RequestPermissionTokenRequest) XXX_Size() int {
	return xxx_messageInfo_RequestPermissionTokenRequest.Size(m)
}
func (m *RequestPermissionTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestPermissionTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestPermissionTokenRequest proto.InternalMessageInfo

func (m *RequestPermissionTokenRequest) GetRequesterProfile() *BasicProfile {
	if m != nil {
		return m.RequesterProfile
	}
	return nil
}

func (m *RequestPermissionTokenRequest) GetPermissionMethod() *PermissionMethod {
	if m != nil {
		return m.PermissionMethod
	}
	return nil
}

func (m *RequestPermissionTokenRequest) GetRequester() *Actor {
	if m != nil {
		return m.Requester
	}
	return nil
}

func (m *RequestPermissionTokenRequest) GetPatient() *Actor {
	if m != nil {
		return m.Patient
	}
	return nil
}

func (m *RequestPermissionTokenRequest) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

// RequestPermissionTokenResponse is response after requesting for permission token
type RequestPermissionTokenResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestPermissionTokenResponse) Reset()         { *m = RequestPermissionTokenResponse{} }
func (m *RequestPermissionTokenResponse) String() string { return proto.CompactTextString(m) }
func (*RequestPermissionTokenResponse) ProtoMessage()    {}
func (*RequestPermissionTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{4}
}

func (m *RequestPermissionTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestPermissionTokenResponse.Unmarshal(m, b)
}
func (m *RequestPermissionTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestPermissionTokenResponse.Marshal(b, m, deterministic)
}
func (m *RequestPermissionTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestPermissionTokenResponse.Merge(m, src)
}
func (m *RequestPermissionTokenResponse) XXX_Size() int {
	return xxx_messageInfo_RequestPermissionTokenResponse.Size(m)
}
func (m *RequestPermissionTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestPermissionTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestPermissionTokenResponse proto.InternalMessageInfo

type GrantPermissionTokenPayload struct {
	Reason               string        `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	RequesterProfile     *BasicProfile `protobuf:"bytes,2,opt,name=requester_profile,json=requesterProfile,proto3" json:"requester_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GrantPermissionTokenPayload) Reset()         { *m = GrantPermissionTokenPayload{} }
func (m *GrantPermissionTokenPayload) String() string { return proto.CompactTextString(m) }
func (*GrantPermissionTokenPayload) ProtoMessage()    {}
func (*GrantPermissionTokenPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{5}
}

func (m *GrantPermissionTokenPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrantPermissionTokenPayload.Unmarshal(m, b)
}
func (m *GrantPermissionTokenPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrantPermissionTokenPayload.Marshal(b, m, deterministic)
}
func (m *GrantPermissionTokenPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrantPermissionTokenPayload.Merge(m, src)
}
func (m *GrantPermissionTokenPayload) XXX_Size() int {
	return xxx_messageInfo_GrantPermissionTokenPayload.Size(m)
}
func (m *GrantPermissionTokenPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_GrantPermissionTokenPayload.DiscardUnknown(m)
}

var xxx_messageInfo_GrantPermissionTokenPayload proto.InternalMessageInfo

func (m *GrantPermissionTokenPayload) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *GrantPermissionTokenPayload) GetRequesterProfile() *BasicProfile {
	if m != nil {
		return m.RequesterProfile
	}
	return nil
}

// GrantPermissionTokenRequest is request message to grant access to patient data
type GrantPermissionTokenRequest struct {
	Requester            *Actor                       `protobuf:"bytes,1,opt,name=requester,proto3" json:"requester,omitempty"`
	Organization         *Actor                       `protobuf:"bytes,2,opt,name=organization,proto3" json:"organization,omitempty"`
	Patient              *Actor                       `protobuf:"bytes,3,opt,name=patient,proto3" json:"patient,omitempty"`
	Payload              *GrantPermissionTokenPayload `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	AuthorizationToken   string                       `protobuf:"bytes,5,opt,name=authorization_token,json=authorizationToken,proto3" json:"authorization_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *GrantPermissionTokenRequest) Reset()         { *m = GrantPermissionTokenRequest{} }
func (m *GrantPermissionTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GrantPermissionTokenRequest) ProtoMessage()    {}
func (*GrantPermissionTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{6}
}

func (m *GrantPermissionTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrantPermissionTokenRequest.Unmarshal(m, b)
}
func (m *GrantPermissionTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrantPermissionTokenRequest.Marshal(b, m, deterministic)
}
func (m *GrantPermissionTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrantPermissionTokenRequest.Merge(m, src)
}
func (m *GrantPermissionTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GrantPermissionTokenRequest.Size(m)
}
func (m *GrantPermissionTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GrantPermissionTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GrantPermissionTokenRequest proto.InternalMessageInfo

func (m *GrantPermissionTokenRequest) GetRequester() *Actor {
	if m != nil {
		return m.Requester
	}
	return nil
}

func (m *GrantPermissionTokenRequest) GetOrganization() *Actor {
	if m != nil {
		return m.Organization
	}
	return nil
}

func (m *GrantPermissionTokenRequest) GetPatient() *Actor {
	if m != nil {
		return m.Patient
	}
	return nil
}

func (m *GrantPermissionTokenRequest) GetPayload() *GrantPermissionTokenPayload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GrantPermissionTokenRequest) GetAuthorizationToken() string {
	if m != nil {
		return m.AuthorizationToken
	}
	return ""
}

// GrantPermissionTokenResponse is response after granting permission to a patient data
type GrantPermissionTokenResponse struct {
	AllowedMessage       string   `protobuf:"bytes,1,opt,name=allowed_message,json=allowedMessage,proto3" json:"allowed_message,omitempty"`
	OperationHash        string   `protobuf:"bytes,2,opt,name=operation_hash,json=operationHash,proto3" json:"operation_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrantPermissionTokenResponse) Reset()         { *m = GrantPermissionTokenResponse{} }
func (m *GrantPermissionTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GrantPermissionTokenResponse) ProtoMessage()    {}
func (*GrantPermissionTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{7}
}

func (m *GrantPermissionTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrantPermissionTokenResponse.Unmarshal(m, b)
}
func (m *GrantPermissionTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrantPermissionTokenResponse.Marshal(b, m, deterministic)
}
func (m *GrantPermissionTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrantPermissionTokenResponse.Merge(m, src)
}
func (m *GrantPermissionTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GrantPermissionTokenResponse.Size(m)
}
func (m *GrantPermissionTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GrantPermissionTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GrantPermissionTokenResponse proto.InternalMessageInfo

func (m *GrantPermissionTokenResponse) GetAllowedMessage() string {
	if m != nil {
		return m.AllowedMessage
	}
	return ""
}

func (m *GrantPermissionTokenResponse) GetOperationHash() string {
	if m != nil {
		return m.OperationHash
	}
	return ""
}

// RevokePermissionTokenRequest is request to revoke permission token
type RevokePermissionTokenRequest struct {
	PatientId            string   `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	RequesterId          string   `protobuf:"bytes,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokePermissionTokenRequest) Reset()         { *m = RevokePermissionTokenRequest{} }
func (m *RevokePermissionTokenRequest) String() string { return proto.CompactTextString(m) }
func (*RevokePermissionTokenRequest) ProtoMessage()    {}
func (*RevokePermissionTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{8}
}

func (m *RevokePermissionTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokePermissionTokenRequest.Unmarshal(m, b)
}
func (m *RevokePermissionTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokePermissionTokenRequest.Marshal(b, m, deterministic)
}
func (m *RevokePermissionTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokePermissionTokenRequest.Merge(m, src)
}
func (m *RevokePermissionTokenRequest) XXX_Size() int {
	return xxx_messageInfo_RevokePermissionTokenRequest.Size(m)
}
func (m *RevokePermissionTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokePermissionTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevokePermissionTokenRequest proto.InternalMessageInfo

func (m *RevokePermissionTokenRequest) GetPatientId() string {
	if m != nil {
		return m.PatientId
	}
	return ""
}

func (m *RevokePermissionTokenRequest) GetRequesterId() string {
	if m != nil {
		return m.RequesterId
	}
	return ""
}

// RevokePermissionTokenResponse is response after revoking permission
type RevokePermissionTokenResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokePermissionTokenResponse) Reset()         { *m = RevokePermissionTokenResponse{} }
func (m *RevokePermissionTokenResponse) String() string { return proto.CompactTextString(m) }
func (*RevokePermissionTokenResponse) ProtoMessage()    {}
func (*RevokePermissionTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{9}
}

func (m *RevokePermissionTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokePermissionTokenResponse.Unmarshal(m, b)
}
func (m *RevokePermissionTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokePermissionTokenResponse.Marshal(b, m, deterministic)
}
func (m *RevokePermissionTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokePermissionTokenResponse.Merge(m, src)
}
func (m *RevokePermissionTokenResponse) XXX_Size() int {
	return xxx_messageInfo_RevokePermissionTokenResponse.Size(m)
}
func (m *RevokePermissionTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokePermissionTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RevokePermissionTokenResponse proto.InternalMessageInfo

// GetPermissionTokenRequest is request to get permission token
type GetPermissionTokenRequest struct {
	PatientId            string   `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	Actor                *Actor   `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPermissionTokenRequest) Reset()         { *m = GetPermissionTokenRequest{} }
func (m *GetPermissionTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetPermissionTokenRequest) ProtoMessage()    {}
func (*GetPermissionTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{10}
}

func (m *GetPermissionTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPermissionTokenRequest.Unmarshal(m, b)
}
func (m *GetPermissionTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPermissionTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetPermissionTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPermissionTokenRequest.Merge(m, src)
}
func (m *GetPermissionTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetPermissionTokenRequest.Size(m)
}
func (m *GetPermissionTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPermissionTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPermissionTokenRequest proto.InternalMessageInfo

func (m *GetPermissionTokenRequest) GetPatientId() string {
	if m != nil {
		return m.PatientId
	}
	return ""
}

func (m *GetPermissionTokenRequest) GetActor() *Actor {
	if m != nil {
		return m.Actor
	}
	return nil
}

// GetPermissionTokenResponse is response after requesting for permission token
type GetPermissionTokenResponse struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Allowed              bool     `protobuf:"varint,2,opt,name=allowed,proto3" json:"allowed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPermissionTokenResponse) Reset()         { *m = GetPermissionTokenResponse{} }
func (m *GetPermissionTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetPermissionTokenResponse) ProtoMessage()    {}
func (*GetPermissionTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{11}
}

func (m *GetPermissionTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPermissionTokenResponse.Unmarshal(m, b)
}
func (m *GetPermissionTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPermissionTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetPermissionTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPermissionTokenResponse.Merge(m, src)
}
func (m *GetPermissionTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetPermissionTokenResponse.Size(m)
}
func (m *GetPermissionTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPermissionTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPermissionTokenResponse proto.InternalMessageInfo

func (m *GetPermissionTokenResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GetPermissionTokenResponse) GetAllowed() bool {
	if m != nil {
		return m.Allowed
	}
	return false
}

// GetActivePermissionsRequest is request to get list of active permissions
type GetActivePermissionsRequest struct {
	PatientId            string   `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetActivePermissionsRequest) Reset()         { *m = GetActivePermissionsRequest{} }
func (m *GetActivePermissionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetActivePermissionsRequest) ProtoMessage()    {}
func (*GetActivePermissionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{12}
}

func (m *GetActivePermissionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActivePermissionsRequest.Unmarshal(m, b)
}
func (m *GetActivePermissionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActivePermissionsRequest.Marshal(b, m, deterministic)
}
func (m *GetActivePermissionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActivePermissionsRequest.Merge(m, src)
}
func (m *GetActivePermissionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetActivePermissionsRequest.Size(m)
}
func (m *GetActivePermissionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActivePermissionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetActivePermissionsRequest proto.InternalMessageInfo

func (m *GetActivePermissionsRequest) GetPatientId() string {
	if m != nil {
		return m.PatientId
	}
	return ""
}

// GetActivePermissionsResponse is a collection of active permissions profiles
type GetActivePermissionsResponse struct {
	ActiveProfiles       []*BasicProfile `protobuf:"bytes,1,rep,name=active_profiles,json=activeProfiles,proto3" json:"active_profiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetActivePermissionsResponse) Reset()         { *m = GetActivePermissionsResponse{} }
func (m *GetActivePermissionsResponse) String() string { return proto.CompactTextString(m) }
func (*GetActivePermissionsResponse) ProtoMessage()    {}
func (*GetActivePermissionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c837ef01cbda0ad8, []int{13}
}

func (m *GetActivePermissionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActivePermissionsResponse.Unmarshal(m, b)
}
func (m *GetActivePermissionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActivePermissionsResponse.Marshal(b, m, deterministic)
}
func (m *GetActivePermissionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActivePermissionsResponse.Merge(m, src)
}
func (m *GetActivePermissionsResponse) XXX_Size() int {
	return xxx_messageInfo_GetActivePermissionsResponse.Size(m)
}
func (m *GetActivePermissionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActivePermissionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetActivePermissionsResponse proto.InternalMessageInfo

func (m *GetActivePermissionsResponse) GetActiveProfiles() []*BasicProfile {
	if m != nil {
		return m.ActiveProfiles
	}
	return nil
}

func init() {
	proto.RegisterEnum("umrs.permission.RequestPermissionMethod", RequestPermissionMethod_name, RequestPermissionMethod_value)
	proto.RegisterType((*BasicProfile)(nil), "umrs.permission.BasicProfile")
	proto.RegisterType((*PermissionMethod)(nil), "umrs.permission.PermissionMethod")
	proto.RegisterMapType((map[string]string)(nil), "umrs.permission.PermissionMethod.MetadataEntry")
	proto.RegisterType((*Actor)(nil), "umrs.permission.Actor")
	proto.RegisterType((*RequestPermissionTokenRequest)(nil), "umrs.permission.RequestPermissionTokenRequest")
	proto.RegisterType((*RequestPermissionTokenResponse)(nil), "umrs.permission.RequestPermissionTokenResponse")
	proto.RegisterType((*GrantPermissionTokenPayload)(nil), "umrs.permission.GrantPermissionTokenPayload")
	proto.RegisterType((*GrantPermissionTokenRequest)(nil), "umrs.permission.GrantPermissionTokenRequest")
	proto.RegisterType((*GrantPermissionTokenResponse)(nil), "umrs.permission.GrantPermissionTokenResponse")
	proto.RegisterType((*RevokePermissionTokenRequest)(nil), "umrs.permission.RevokePermissionTokenRequest")
	proto.RegisterType((*RevokePermissionTokenResponse)(nil), "umrs.permission.RevokePermissionTokenResponse")
	proto.RegisterType((*GetPermissionTokenRequest)(nil), "umrs.permission.GetPermissionTokenRequest")
	proto.RegisterType((*GetPermissionTokenResponse)(nil), "umrs.permission.GetPermissionTokenResponse")
	proto.RegisterType((*GetActivePermissionsRequest)(nil), "umrs.permission.GetActivePermissionsRequest")
	proto.RegisterType((*GetActivePermissionsResponse)(nil), "umrs.permission.GetActivePermissionsResponse")
}

func init() { proto.RegisterFile("permission.proto", fileDescriptor_c837ef01cbda0ad8) }

var fileDescriptor_c837ef01cbda0ad8 = []byte{
	// 1107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xcf, 0x52, 0x23, 0x45,
	0x18, 0x77, 0x26, 0x24, 0xc0, 0x17, 0x36, 0x0c, 0x2d, 0x62, 0x0c, 0xa0, 0x30, 0x55, 0x96, 0x14,
	0x0b, 0x99, 0xad, 0xb8, 0x07, 0x8b, 0xd5, 0xaa, 0x0d, 0x08, 0xec, 0xec, 0x2e, 0x21, 0x35, 0x80,
	0x96, 0x5e, 0xc6, 0xde, 0x4c, 0x93, 0x4c, 0x31, 0x99, 0x8e, 0xd3, 0x1d, 0x28, 0xa4, 0x3c, 0xe8,
	0x2b, 0x78, 0xf6, 0xe4, 0xc1, 0xa3, 0x55, 0x1e, 0xb5, 0x3c, 0xf8, 0x0c, 0xbe, 0x82, 0x0f, 0xe1,
	0xd1, 0xea, 0x9e, 0x4e, 0x32, 0x21, 0x13, 0xc8, 0xee, 0x89, 0xe9, 0xaf, 0x7f, 0xdf, 0xbf, 0xdf,
	0xf7, 0xa7, 0x09, 0x18, 0x1d, 0x12, 0xb5, 0x7d, 0xc6, 0x7c, 0x1a, 0x96, 0x3b, 0x11, 0xe5, 0x14,
	0xcd, 0xb7, 0x1b, 0xe7, 0x9d, 0xf2, 0x40, 0x5c, 0x5a, 0x69, 0x52, 0xda, 0x0c, 0x88, 0x85, 0x3b,
	0xbe, 0x85, 0xc3, 0x90, 0x72, 0xcc, 0x7d, 0x1a, 0xb2, 0x18, 0x5e, 0xda, 0x92, 0x7f, 0x1a, 0xdb,
	0x4d, 0x12, 0x6e, 0xb3, 0x2b, 0xdc, 0x6c, 0x92, 0xc8, 0xa2, 0x1d, 0x89, 0x18, 0x45, 0x9b, 0x3f,
	0xeb, 0x30, 0xb7, 0x8b, 0x99, 0xdf, 0xa8, 0x47, 0xf4, 0xdc, 0x0f, 0x08, 0x5a, 0x05, 0xc0, 0x8d,
	0x06, 0xed, 0x86, 0xdc, 0xf5, 0xbd, 0xa2, 0xb6, 0xa6, 0x6d, 0xcc, 0x3a, 0xb3, 0x4a, 0x62, 0x7b,
	0x68, 0x19, 0x66, 0xcf, 0xbb, 0x41, 0xe0, 0x86, 0xb8, 0x4d, 0x8a, 0xba, 0xbc, 0x9d, 0x11, 0x82,
	0x1a, 0x6e, 0x13, 0xb4, 0x09, 0x0b, 0x9d, 0xd8, 0x8c, 0xcb, 0x5b, 0xdd, 0xf6, 0x2b, 0xb7, 0x1b,
	0x05, 0xc5, 0x8c, 0x04, 0xcd, 0xab, 0x8b, 0x53, 0x21, 0x3f, 0x8b, 0x02, 0xf4, 0x08, 0x16, 0x23,
	0x1a, 0x10, 0x17, 0x73, 0x97, 0x46, 0x4d, 0x1c, 0xfa, 0xdf, 0xc9, 0xb8, 0x8a, 0x53, 0x12, 0x8e,
	0xc4, 0x5d, 0x95, 0x1f, 0x27, 0x6e, 0xd0, 0x43, 0x58, 0x48, 0x22, 0xe3, 0x10, 0xb2, 0x12, 0x6e,
	0x24, 0x2f, 0x64, 0x28, 0x1f, 0xc1, 0xfc, 0x10, 0xd8, 0xf7, 0x8a, 0x39, 0x09, 0x2d, 0x24, 0xc5,
	0xb6, 0x27, 0xf2, 0xbd, 0xa2, 0xd1, 0x85, 0x4b, 0xda, 0xd8, 0x0f, 0x8a, 0xd3, 0x71, 0xbe, 0x42,
	0xb2, 0x2f, 0x04, 0xe6, 0x7f, 0x1a, 0x18, 0xf5, 0x3e, 0xf5, 0x47, 0x84, 0xb7, 0xa8, 0x87, 0x9e,
	0x42, 0xae, 0x2d, 0xbf, 0x24, 0x3f, 0x85, 0xca, 0x46, 0xf9, 0x56, 0x89, 0xca, 0x0e, 0xf9, 0xb6,
	0x4b, 0x18, 0xbf, 0xad, 0xe9, 0x28, 0x3d, 0x54, 0x84, 0xe9, 0x0e, 0xbe, 0x0e, 0x28, 0xf6, 0x14,
	0x89, 0xbd, 0x23, 0x7a, 0x01, 0x33, 0x6d, 0xc2, 0xb1, 0x87, 0x39, 0x2e, 0x66, 0xd6, 0x32, 0x1b,
	0xf9, 0x8a, 0x35, 0x62, 0xfd, 0xb6, 0xd9, 0xf2, 0x91, 0xd2, 0xd8, 0x0f, 0x79, 0x74, 0xed, 0xf4,
	0x0d, 0x94, 0x9e, 0xc0, 0x83, 0xa1, 0x2b, 0x64, 0x40, 0xe6, 0x82, 0x5c, 0xab, 0xb2, 0x8a, 0x4f,
	0xb4, 0x08, 0xd9, 0x4b, 0x1c, 0x74, 0x7b, 0xc5, 0x8c, 0x0f, 0x3b, 0xfa, 0x27, 0x9a, 0xf9, 0x1c,
	0xb2, 0xd5, 0x06, 0xa7, 0x91, 0x80, 0x34, 0x23, 0xda, 0xed, 0x48, 0xb5, 0xac, 0x13, 0x1f, 0x50,
	0x01, 0x74, 0xbf, 0x17, 0xbd, 0xee, 0xdf, 0xea, 0x8c, 0xcc, 0x70, 0x67, 0x98, 0x7f, 0xea, 0xb0,
	0x3a, 0xc2, 0xc9, 0x29, 0xbd, 0x20, 0xa1, 0x92, 0xa2, 0xe7, 0xb0, 0x10, 0xc5, 0x9f, 0x24, 0x72,
	0x55, 0xb3, 0x48, 0x87, 0xf9, 0xca, 0xea, 0x08, 0x01, 0xc9, 0x8e, 0x75, 0x8c, 0xbe, 0x5e, 0xaf,
	0x87, 0x6b, 0xb0, 0x30, 0x00, 0xbb, 0xaa, 0x54, 0xba, 0xb4, 0xb5, 0x7e, 0x2f, 0x99, 0x4e, 0x62,
	0x02, 0x55, 0xbd, 0x1f, 0xc3, 0x6c, 0xdf, 0x87, 0x4c, 0x2d, 0x5f, 0x59, 0x1a, 0xb1, 0x23, 0xb9,
	0x72, 0x06, 0x40, 0xf4, 0x48, 0xd4, 0x98, 0xfb, 0x24, 0xe4, 0xb2, 0xa9, 0xc7, 0xeb, 0xf4, 0x60,
	0x68, 0x09, 0x72, 0x11, 0xc1, 0x8c, 0x86, 0xaa, 0xad, 0xd5, 0xc9, 0x5c, 0x83, 0xf7, 0xc7, 0x91,
	0xc7, 0x3a, 0x34, 0x64, 0xc4, 0xfc, 0x41, 0x83, 0xe5, 0xc3, 0x08, 0x87, 0xb7, 0x01, 0x75, 0xd5,
	0x55, 0x03, 0xcb, 0x5a, 0xd2, 0x72, 0x3a, 0xeb, 0xfa, 0x1b, 0xb1, 0x6e, 0xfe, 0xa1, 0xa7, 0xc7,
	0xd0, 0xab, 0xf0, 0x10, 0x8b, 0xda, 0xa4, 0x2c, 0xee, 0xc0, 0xdc, 0xd0, 0x7e, 0xd0, 0xef, 0x54,
	0x1c, 0xc2, 0x26, 0x2b, 0x90, 0x99, 0xac, 0x02, 0x07, 0x83, 0xb9, 0x8c, 0x6b, 0xb6, 0x35, 0xa2,
	0x71, 0x07, 0xcd, 0x83, 0x29, 0xb6, 0xe0, 0x6d, 0xdc, 0xe5, 0x2d, 0x1a, 0xf5, 0xf6, 0x0f, 0x17,
	0x30, 0x55, 0x56, 0x34, 0x74, 0x25, 0x0d, 0x98, 0x21, 0xac, 0xa4, 0x73, 0x17, 0x17, 0x58, 0xec,
	0x33, 0x1c, 0x04, 0xf4, 0x8a, 0x78, 0x6e, 0x9b, 0x30, 0x86, 0x9b, 0x44, 0x55, 0xb2, 0xa0, 0xc4,
	0x47, 0xb1, 0x14, 0x7d, 0x08, 0x05, 0xda, 0x21, 0x51, 0xec, 0xb5, 0x85, 0x59, 0x4b, 0x8d, 0xe8,
	0x83, 0xbe, 0xf4, 0x19, 0x66, 0x2d, 0xf3, 0x1b, 0x58, 0x71, 0xc8, 0x25, 0xbd, 0x20, 0x63, 0x8a,
	0xb5, 0x0a, 0xa0, 0x38, 0x49, 0x3c, 0x03, 0x4a, 0x62, 0x7b, 0x68, 0x1d, 0xe6, 0x06, 0x7d, 0xd3,
	0x5f, 0x03, 0xf9, 0xbe, 0xcc, 0xf6, 0xcc, 0x0f, 0xc4, 0xc4, 0xa7, 0x7a, 0x50, 0x3d, 0xdb, 0x82,
	0xf7, 0x0e, 0x09, 0x7f, 0x33, 0xff, 0x5b, 0x90, 0xc5, 0xa2, 0x72, 0xf7, 0xb4, 0x43, 0x0c, 0x32,
	0xbf, 0x82, 0x52, 0x9a, 0x27, 0x45, 0xed, 0x3a, 0xcc, 0xe1, 0x46, 0x83, 0x30, 0xa6, 0x8a, 0x14,
	0x3b, 0xcb, 0xc7, 0x32, 0x09, 0x15, 0xeb, 0x5a, 0xd1, 0x2c, 0x1d, 0xce, 0x38, 0xbd, 0xa3, 0xf9,
	0x29, 0x2c, 0x1f, 0x12, 0x5e, 0x6d, 0x70, 0xff, 0x32, 0x91, 0x28, 0x9b, 0x2c, 0x0d, 0xf3, 0x1c,
	0x56, 0xd2, 0xb5, 0x55, 0x68, 0x07, 0x30, 0x8f, 0xe5, 0x65, 0x6f, 0x36, 0x59, 0x51, 0x93, 0x6f,
	0xc2, 0x3d, 0xc3, 0x59, 0x88, 0xb5, 0xd4, 0x91, 0x6d, 0x06, 0xf0, 0xee, 0x98, 0x17, 0x09, 0xe5,
	0x61, 0xfa, 0xac, 0xf6, 0xa2, 0x76, 0xfc, 0x65, 0xcd, 0x78, 0x0b, 0xcd, 0x42, 0x76, 0xff, 0xa8,
	0x6a, 0xbf, 0x34, 0x34, 0x34, 0x0d, 0x99, 0x93, 0xa3, 0x13, 0x43, 0x47, 0x33, 0x30, 0x75, 0x76,
	0x72, 0xf2, 0xb9, 0x91, 0x41, 0xf3, 0x90, 0x3f, 0xb0, 0x6b, 0x87, 0xfb, 0x4e, 0xdd, 0xb1, 0x6b,
	0xa7, 0xc6, 0x94, 0x80, 0x7f, 0x71, 0x6c, 0xef, 0xed, 0x1b, 0x59, 0x04, 0x90, 0x3b, 0xa8, 0xee,
	0xd9, 0xd5, 0x97, 0x46, 0xae, 0xf2, 0xeb, 0x34, 0x2c, 0xd6, 0xe3, 0x1c, 0x07, 0xee, 0xaa, 0x75,
	0x1b, 0xfd, 0xa2, 0xc1, 0x52, 0xfa, 0x22, 0x43, 0xe5, 0xfb, 0x9f, 0xd0, 0x64, 0x7f, 0x94, 0xac,
	0x89, 0xf1, 0xaa, 0xdb, 0x36, 0x7e, 0xfc, 0xe7, 0xdf, 0x9f, 0x74, 0xd3, 0x5c, 0x95, 0xff, 0x36,
	0x09, 0x65, 0x6b, 0xa0, 0xcc, 0x2c, 0xd5, 0xb9, 0x3b, 0xda, 0x26, 0xfa, 0x4b, 0x83, 0xc5, 0xb4,
	0x59, 0x44, 0x93, 0xed, 0x82, 0x5e, 0x84, 0xdb, 0x13, 0xa2, 0x55, 0x7c, 0xcf, 0x64, 0x7c, 0xbb,
	0xe8, 0x69, 0x7a, 0x7c, 0xaa, 0x67, 0xac, 0x1b, 0xf5, 0x51, 0xf6, 0xbd, 0xef, 0xad, 0xa6, 0x30,
	0xc8, 0xac, 0x9b, 0xfe, 0xd8, 0x09, 0x29, 0xfa, 0x5b, 0x83, 0x77, 0x52, 0x27, 0x0f, 0x6d, 0xa7,
	0x90, 0x36, 0x7e, 0x07, 0x94, 0xca, 0x93, 0xc2, 0x55, 0x0a, 0xb6, 0x4c, 0x61, 0x0f, 0x55, 0x27,
	0x4b, 0xc1, 0x15, 0x29, 0x44, 0xd2, 0x62, 0x32, 0x07, 0x21, 0x46, 0xbf, 0x6b, 0x80, 0x46, 0x47,
	0x16, 0x6d, 0x8e, 0x72, 0x3a, 0x6e, 0x83, 0x94, 0x1e, 0x4e, 0x84, 0x55, 0xa1, 0xef, 0xc9, 0xd0,
	0x3f, 0x43, 0x4f, 0x5e, 0x23, 0x74, 0xb9, 0x2d, 0xac, 0x1b, 0xb9, 0x62, 0x24, 0xf1, 0xbf, 0x89,
	0xc6, 0x49, 0x19, 0xe7, 0xb4, 0xc6, 0x19, 0xbf, 0x33, 0xd2, 0x1a, 0xe7, 0x8e, 0x1d, 0x61, 0xee,
	0xc8, 0xd0, 0x1f, 0xa3, 0xca, 0x6b, 0x84, 0xae, 0xb6, 0xd7, 0xee, 0xdc, 0xd7, 0x30, 0xc0, 0xbe,
	0xca, 0xc9, 0x9f, 0x04, 0x1f, 0xff, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x07, 0xe4, 0xe0, 0x85, 0x83,
	0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PatientPermissionAPIClient is the client API for PatientPermissionAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PatientPermissionAPIClient interface {
	// Request to access medical data of patient
	RequestPermissionToken(ctx context.Context, in *RequestPermissionTokenRequest, opts ...grpc.CallOption) (*RequestPermissionTokenResponse, error)
	// Grant permission to an actor requesting medical data
	GrantPermissionToken(ctx context.Context, in *GrantPermissionTokenRequest, opts ...grpc.CallOption) (*GrantPermissionTokenResponse, error)
	// Revokes a permission token
	RevokePermissionToken(ctx context.Context, in *RevokePermissionTokenRequest, opts ...grpc.CallOption) (*RevokePermissionTokenResponse, error)
	// Fetches permission token
	GetPermissionToken(ctx context.Context, in *GetPermissionTokenRequest, opts ...grpc.CallOption) (*GetPermissionTokenResponse, error)
	// Get list of actor allowed access
	GetActivePermissions(ctx context.Context, in *GetActivePermissionsRequest, opts ...grpc.CallOption) (*GetActivePermissionsResponse, error)
}

type patientPermissionAPIClient struct {
	cc *grpc.ClientConn
}

func NewPatientPermissionAPIClient(cc *grpc.ClientConn) PatientPermissionAPIClient {
	return &patientPermissionAPIClient{cc}
}

func (c *patientPermissionAPIClient) RequestPermissionToken(ctx context.Context, in *RequestPermissionTokenRequest, opts ...grpc.CallOption) (*RequestPermissionTokenResponse, error) {
	out := new(RequestPermissionTokenResponse)
	err := c.cc.Invoke(ctx, "/umrs.permission.PatientPermissionAPI/RequestPermissionToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patientPermissionAPIClient) GrantPermissionToken(ctx context.Context, in *GrantPermissionTokenRequest, opts ...grpc.CallOption) (*GrantPermissionTokenResponse, error) {
	out := new(GrantPermissionTokenResponse)
	err := c.cc.Invoke(ctx, "/umrs.permission.PatientPermissionAPI/GrantPermissionToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patientPermissionAPIClient) RevokePermissionToken(ctx context.Context, in *RevokePermissionTokenRequest, opts ...grpc.CallOption) (*RevokePermissionTokenResponse, error) {
	out := new(RevokePermissionTokenResponse)
	err := c.cc.Invoke(ctx, "/umrs.permission.PatientPermissionAPI/RevokePermissionToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patientPermissionAPIClient) GetPermissionToken(ctx context.Context, in *GetPermissionTokenRequest, opts ...grpc.CallOption) (*GetPermissionTokenResponse, error) {
	out := new(GetPermissionTokenResponse)
	err := c.cc.Invoke(ctx, "/umrs.permission.PatientPermissionAPI/GetPermissionToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patientPermissionAPIClient) GetActivePermissions(ctx context.Context, in *GetActivePermissionsRequest, opts ...grpc.CallOption) (*GetActivePermissionsResponse, error) {
	out := new(GetActivePermissionsResponse)
	err := c.cc.Invoke(ctx, "/umrs.permission.PatientPermissionAPI/GetActivePermissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PatientPermissionAPIServer is the server API for PatientPermissionAPI service.
type PatientPermissionAPIServer interface {
	// Request to access medical data of patient
	RequestPermissionToken(context.Context, *RequestPermissionTokenRequest) (*RequestPermissionTokenResponse, error)
	// Grant permission to an actor requesting medical data
	GrantPermissionToken(context.Context, *GrantPermissionTokenRequest) (*GrantPermissionTokenResponse, error)
	// Revokes a permission token
	RevokePermissionToken(context.Context, *RevokePermissionTokenRequest) (*RevokePermissionTokenResponse, error)
	// Fetches permission token
	GetPermissionToken(context.Context, *GetPermissionTokenRequest) (*GetPermissionTokenResponse, error)
	// Get list of actor allowed access
	GetActivePermissions(context.Context, *GetActivePermissionsRequest) (*GetActivePermissionsResponse, error)
}

func RegisterPatientPermissionAPIServer(s *grpc.Server, srv PatientPermissionAPIServer) {
	s.RegisterService(&_PatientPermissionAPI_serviceDesc, srv)
}

func _PatientPermissionAPI_RequestPermissionToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPermissionTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientPermissionAPIServer).RequestPermissionToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umrs.permission.PatientPermissionAPI/RequestPermissionToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientPermissionAPIServer).RequestPermissionToken(ctx, req.(*RequestPermissionTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatientPermissionAPI_GrantPermissionToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantPermissionTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientPermissionAPIServer).GrantPermissionToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umrs.permission.PatientPermissionAPI/GrantPermissionToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientPermissionAPIServer).GrantPermissionToken(ctx, req.(*GrantPermissionTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatientPermissionAPI_RevokePermissionToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokePermissionTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientPermissionAPIServer).RevokePermissionToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umrs.permission.PatientPermissionAPI/RevokePermissionToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientPermissionAPIServer).RevokePermissionToken(ctx, req.(*RevokePermissionTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatientPermissionAPI_GetPermissionToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPermissionTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientPermissionAPIServer).GetPermissionToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umrs.permission.PatientPermissionAPI/GetPermissionToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientPermissionAPIServer).GetPermissionToken(ctx, req.(*GetPermissionTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatientPermissionAPI_GetActivePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActivePermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientPermissionAPIServer).GetActivePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umrs.permission.PatientPermissionAPI/GetActivePermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientPermissionAPIServer).GetActivePermissions(ctx, req.(*GetActivePermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PatientPermissionAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "umrs.permission.PatientPermissionAPI",
	HandlerType: (*PatientPermissionAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestPermissionToken",
			Handler:    _PatientPermissionAPI_RequestPermissionToken_Handler,
		},
		{
			MethodName: "GrantPermissionToken",
			Handler:    _PatientPermissionAPI_GrantPermissionToken_Handler,
		},
		{
			MethodName: "RevokePermissionToken",
			Handler:    _PatientPermissionAPI_RevokePermissionToken_Handler,
		},
		{
			MethodName: "GetPermissionToken",
			Handler:    _PatientPermissionAPI_GetPermissionToken_Handler,
		},
		{
			MethodName: "GetActivePermissions",
			Handler:    _PatientPermissionAPI_GetActivePermissions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "permission.proto",
}
