// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package account

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// AccountType is the type of an account
type AccountType int32

const (
	AccountType_ADMIN_VIEWER AccountType = 0
	AccountType_ADMIN_OWNER  AccountType = 1
	AccountType_ADMIN_EDITOR AccountType = 2
	AccountType_USER_OWNER   AccountType = 3
)

var AccountType_name = map[int32]string{
	0: "ADMIN_VIEWER",
	1: "ADMIN_OWNER",
	2: "ADMIN_EDITOR",
	3: "USER_OWNER",
}

var AccountType_value = map[string]int32{
	"ADMIN_VIEWER": 0,
	"ADMIN_OWNER":  1,
	"ADMIN_EDITOR": 2,
	"USER_OWNER":   3,
}

func (x AccountType) String() string {
	return proto.EnumName(AccountType_name, int32(x))
}

func (AccountType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

// AccountState represent the state of an account at any point
type AccountState int32

const (
	AccountState_BLOCKED  AccountState = 0
	AccountState_ACTIVE   AccountState = 1
	AccountState_INACTIVE AccountState = 2
)

var AccountState_name = map[int32]string{
	0: "BLOCKED",
	1: "ACTIVE",
	2: "INACTIVE",
}

var AccountState_value = map[string]int32{
	"BLOCKED":  0,
	"ACTIVE":   1,
	"INACTIVE": 2,
}

func (x AccountState) String() string {
	return proto.EnumName(AccountState_name, int32(x))
}

func (AccountState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

// AccountView returns only subset of account information
type AccountView int32

const (
	AccountView_FULL_VIEW   AccountView = 0
	AccountView_LIST_VIEW   AccountView = 1
	AccountView_SEARCH_VIEW AccountView = 2
	AccountView_BASIC_VIEW  AccountView = 3
)

var AccountView_name = map[int32]string{
	0: "FULL_VIEW",
	1: "LIST_VIEW",
	2: "SEARCH_VIEW",
	3: "BASIC_VIEW",
}

var AccountView_value = map[string]int32{
	"FULL_VIEW":   0,
	"LIST_VIEW":   1,
	"SEARCH_VIEW": 2,
	"BASIC_VIEW":  3,
}

func (x AccountView) String() string {
	return proto.EnumName(AccountView_name, int32(x))
}

func (AccountView) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

// Account contains information about user entity. Can be a user or admin
type Account struct {
	AccountId            string       `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	NationalId           string       `protobuf:"bytes,2,opt,name=national_id,json=nationalId,proto3" json:"national_id,omitempty"`
	Email                string       `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string       `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	FirstName            string       `protobuf:"bytes,5,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string       `protobuf:"bytes,6,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	BirthDate            string       `protobuf:"bytes,7,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Gender               string       `protobuf:"bytes,8,opt,name=gender,proto3" json:"gender,omitempty"`
	Nationality          string       `protobuf:"bytes,9,opt,name=nationality,proto3" json:"nationality,omitempty"`
	ProfileUrlThumb      string       `protobuf:"bytes,10,opt,name=profile_url_thumb,json=profileUrlThumb,proto3" json:"profile_url_thumb,omitempty"`
	ProfileUrlNormal     string       `protobuf:"bytes,11,opt,name=profile_url_normal,json=profileUrlNormal,proto3" json:"profile_url_normal,omitempty"`
	AccountType          AccountType  `protobuf:"varint,12,opt,name=account_type,json=accountType,proto3,enum=umrs.account.AccountType" json:"account_type,omitempty"`
	AccountState         AccountState `protobuf:"varint,13,opt,name=account_state,json=accountState,proto3,enum=umrs.account.AccountState" json:"account_state,omitempty"`
	AccountLabels        []string     `protobuf:"bytes,14,rep,name=account_labels,json=accountLabels,proto3" json:"account_labels,omitempty"`
	TrustedDevices       []string     `protobuf:"bytes,15,rep,name=trusted_devices,json=trustedDevices,proto3" json:"trusted_devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Account) GetNationalId() string {
	if m != nil {
		return m.NationalId
	}
	return ""
}

func (m *Account) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Account) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Account) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Account) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Account) GetBirthDate() string {
	if m != nil {
		return m.BirthDate
	}
	return ""
}

func (m *Account) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Account) GetNationality() string {
	if m != nil {
		return m.Nationality
	}
	return ""
}

func (m *Account) GetProfileUrlThumb() string {
	if m != nil {
		return m.ProfileUrlThumb
	}
	return ""
}

func (m *Account) GetProfileUrlNormal() string {
	if m != nil {
		return m.ProfileUrlNormal
	}
	return ""
}

func (m *Account) GetAccountType() AccountType {
	if m != nil {
		return m.AccountType
	}
	return AccountType_ADMIN_VIEWER
}

func (m *Account) GetAccountState() AccountState {
	if m != nil {
		return m.AccountState
	}
	return AccountState_BLOCKED
}

func (m *Account) GetAccountLabels() []string {
	if m != nil {
		return m.AccountLabels
	}
	return nil
}

func (m *Account) GetTrustedDevices() []string {
	if m != nil {
		return m.TrustedDevices
	}
	return nil
}

// PrivateAccount contains account sensitive information such as password and security QA
type PrivateAccount struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword      string   `protobuf:"bytes,2,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	SecurityQuestion     string   `protobuf:"bytes,3,opt,name=security_question,json=securityQuestion,proto3" json:"security_question,omitempty"`
	SecurityAnswer       string   `protobuf:"bytes,4,opt,name=security_answer,json=securityAnswer,proto3" json:"security_answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivateAccount) Reset()         { *m = PrivateAccount{} }
func (m *PrivateAccount) String() string { return proto.CompactTextString(m) }
func (*PrivateAccount) ProtoMessage()    {}
func (*PrivateAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *PrivateAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateAccount.Unmarshal(m, b)
}
func (m *PrivateAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateAccount.Marshal(b, m, deterministic)
}
func (m *PrivateAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateAccount.Merge(m, src)
}
func (m *PrivateAccount) XXX_Size() int {
	return xxx_messageInfo_PrivateAccount.Size(m)
}
func (m *PrivateAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateAccount.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateAccount proto.InternalMessageInfo

func (m *PrivateAccount) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *PrivateAccount) GetConfirmPassword() string {
	if m != nil {
		return m.ConfirmPassword
	}
	return ""
}

func (m *PrivateAccount) GetSecurityQuestion() string {
	if m != nil {
		return m.SecurityQuestion
	}
	return ""
}

func (m *PrivateAccount) GetSecurityAnswer() string {
	if m != nil {
		return m.SecurityAnswer
	}
	return ""
}

// SocialProfile is profile information from third parties
type SocialProfile struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	EmailAddress         string   `protobuf:"bytes,4,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	ProfileUrl           string   `protobuf:"bytes,5,opt,name=profile_url,json=profileUrl,proto3" json:"profile_url,omitempty"`
	Gender               string   `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	BirthDate            string   `protobuf:"bytes,7,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocialProfile) Reset()         { *m = SocialProfile{} }
func (m *SocialProfile) String() string { return proto.CompactTextString(m) }
func (*SocialProfile) ProtoMessage()    {}
func (*SocialProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *SocialProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocialProfile.Unmarshal(m, b)
}
func (m *SocialProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocialProfile.Marshal(b, m, deterministic)
}
func (m *SocialProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocialProfile.Merge(m, src)
}
func (m *SocialProfile) XXX_Size() int {
	return xxx_messageInfo_SocialProfile.Size(m)
}
func (m *SocialProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_SocialProfile.DiscardUnknown(m)
}

var xxx_messageInfo_SocialProfile proto.InternalMessageInfo

func (m *SocialProfile) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *SocialProfile) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *SocialProfile) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *SocialProfile) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *SocialProfile) GetProfileUrl() string {
	if m != nil {
		return m.ProfileUrl
	}
	return ""
}

func (m *SocialProfile) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *SocialProfile) GetBirthDate() string {
	if m != nil {
		return m.BirthDate
	}
	return ""
}

// Google is request to login with google
type Google struct {
	GoogleProfile        *SocialProfile `protobuf:"bytes,1,opt,name=google_profile,json=googleProfile,proto3" json:"google_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Google) Reset()         { *m = Google{} }
func (m *Google) String() string { return proto.CompactTextString(m) }
func (*Google) ProtoMessage()    {}
func (*Google) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}

func (m *Google) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Google.Unmarshal(m, b)
}
func (m *Google) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Google.Marshal(b, m, deterministic)
}
func (m *Google) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Google.Merge(m, src)
}
func (m *Google) XXX_Size() int {
	return xxx_messageInfo_Google.Size(m)
}
func (m *Google) XXX_DiscardUnknown() {
	xxx_messageInfo_Google.DiscardUnknown(m)
}

var xxx_messageInfo_Google proto.InternalMessageInfo

func (m *Google) GetGoogleProfile() *SocialProfile {
	if m != nil {
		return m.GoogleProfile
	}
	return nil
}

// Facebook is request to login with facebook
type Facebook struct {
	FbProfile            *SocialProfile `protobuf:"bytes,1,opt,name=fb_profile,json=fbProfile,proto3" json:"fb_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Facebook) Reset()         { *m = Facebook{} }
func (m *Facebook) String() string { return proto.CompactTextString(m) }
func (*Facebook) ProtoMessage()    {}
func (*Facebook) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{4}
}

func (m *Facebook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Facebook.Unmarshal(m, b)
}
func (m *Facebook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Facebook.Marshal(b, m, deterministic)
}
func (m *Facebook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Facebook.Merge(m, src)
}
func (m *Facebook) XXX_Size() int {
	return xxx_messageInfo_Facebook.Size(m)
}
func (m *Facebook) XXX_DiscardUnknown() {
	xxx_messageInfo_Facebook.DiscardUnknown(m)
}

var xxx_messageInfo_Facebook proto.InternalMessageInfo

func (m *Facebook) GetFbProfile() *SocialProfile {
	if m != nil {
		return m.FbProfile
	}
	return nil
}

// Twitter is request to login with twitter
type Twitter struct {
	TwitterProfile       *SocialProfile `protobuf:"bytes,1,opt,name=twitter_profile,json=twitterProfile,proto3" json:"twitter_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Twitter) Reset()         { *m = Twitter{} }
func (m *Twitter) String() string { return proto.CompactTextString(m) }
func (*Twitter) ProtoMessage()    {}
func (*Twitter) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{5}
}

func (m *Twitter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Twitter.Unmarshal(m, b)
}
func (m *Twitter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Twitter.Marshal(b, m, deterministic)
}
func (m *Twitter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Twitter.Merge(m, src)
}
func (m *Twitter) XXX_Size() int {
	return xxx_messageInfo_Twitter.Size(m)
}
func (m *Twitter) XXX_DiscardUnknown() {
	xxx_messageInfo_Twitter.DiscardUnknown(m)
}

var xxx_messageInfo_Twitter proto.InternalMessageInfo

func (m *Twitter) GetTwitterProfile() *SocialProfile {
	if m != nil {
		return m.TwitterProfile
	}
	return nil
}

// Creds is request to login using national_id, email or phone number
type Creds struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	NationalId           string   `protobuf:"bytes,3,opt,name=national_id,json=nationalId,proto3" json:"national_id,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Creds) Reset()         { *m = Creds{} }
func (m *Creds) String() string { return proto.CompactTextString(m) }
func (*Creds) ProtoMessage()    {}
func (*Creds) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{6}
}

func (m *Creds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Creds.Unmarshal(m, b)
}
func (m *Creds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Creds.Marshal(b, m, deterministic)
}
func (m *Creds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Creds.Merge(m, src)
}
func (m *Creds) XXX_Size() int {
	return xxx_messageInfo_Creds.Size(m)
}
func (m *Creds) XXX_DiscardUnknown() {
	xxx_messageInfo_Creds.DiscardUnknown(m)
}

var xxx_messageInfo_Creds proto.InternalMessageInfo

func (m *Creds) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Creds) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Creds) GetNationalId() string {
	if m != nil {
		return m.NationalId
	}
	return ""
}

func (m *Creds) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// LoginRequest is request to login
type LoginRequest struct {
	// User can only use one of the options
	//
	// Types that are valid to be assigned to Login:
	//	*LoginRequest_Facebook
	//	*LoginRequest_Google
	//	*LoginRequest_Twitter
	//	*LoginRequest_Creds
	Login                isLoginRequest_Login `protobuf_oneof:"login"`
	Group                string               `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{7}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

type isLoginRequest_Login interface {
	isLoginRequest_Login()
}

type LoginRequest_Facebook struct {
	Facebook *Facebook `protobuf:"bytes,1,opt,name=facebook,proto3,oneof"`
}

type LoginRequest_Google struct {
	Google *Google `protobuf:"bytes,2,opt,name=google,proto3,oneof"`
}

type LoginRequest_Twitter struct {
	Twitter *Twitter `protobuf:"bytes,3,opt,name=twitter,proto3,oneof"`
}

type LoginRequest_Creds struct {
	Creds *Creds `protobuf:"bytes,4,opt,name=creds,proto3,oneof"`
}

func (*LoginRequest_Facebook) isLoginRequest_Login() {}

func (*LoginRequest_Google) isLoginRequest_Login() {}

func (*LoginRequest_Twitter) isLoginRequest_Login() {}

func (*LoginRequest_Creds) isLoginRequest_Login() {}

func (m *LoginRequest) GetLogin() isLoginRequest_Login {
	if m != nil {
		return m.Login
	}
	return nil
}

func (m *LoginRequest) GetFacebook() *Facebook {
	if x, ok := m.GetLogin().(*LoginRequest_Facebook); ok {
		return x.Facebook
	}
	return nil
}

func (m *LoginRequest) GetGoogle() *Google {
	if x, ok := m.GetLogin().(*LoginRequest_Google); ok {
		return x.Google
	}
	return nil
}

func (m *LoginRequest) GetTwitter() *Twitter {
	if x, ok := m.GetLogin().(*LoginRequest_Twitter); ok {
		return x.Twitter
	}
	return nil
}

func (m *LoginRequest) GetCreds() *Creds {
	if x, ok := m.GetLogin().(*LoginRequest_Creds); ok {
		return x.Creds
	}
	return nil
}

func (m *LoginRequest) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*LoginRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*LoginRequest_Facebook)(nil),
		(*LoginRequest_Google)(nil),
		(*LoginRequest_Twitter)(nil),
		(*LoginRequest_Creds)(nil),
	}
}

// LoginResponse is response after login
type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountState         string   `protobuf:"bytes,3,opt,name=account_state,json=accountState,proto3" json:"account_state,omitempty"`
	AccountType          string   `protobuf:"bytes,4,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	AccountGroup         string   `protobuf:"bytes,5,opt,name=account_group,json=accountGroup,proto3" json:"account_group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{8}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *LoginResponse) GetAccountState() string {
	if m != nil {
		return m.AccountState
	}
	return ""
}

func (m *LoginResponse) GetAccountType() string {
	if m != nil {
		return m.AccountType
	}
	return ""
}

func (m *LoginResponse) GetAccountGroup() string {
	if m != nil {
		return m.AccountGroup
	}
	return ""
}

// CreateRequest is request to create an account
type CreateRequest struct {
	AccountLabel         string          `protobuf:"bytes,1,opt,name=account_label,json=accountLabel,proto3" json:"account_label,omitempty"`
	Account              *Account        `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	PrivateAccount       *PrivateAccount `protobuf:"bytes,3,opt,name=private_account,json=privateAccount,proto3" json:"private_account,omitempty"`
	ByAdmin              bool            `protobuf:"varint,4,opt,name=by_admin,json=byAdmin,proto3" json:"by_admin,omitempty"`
	AdminId              string          `protobuf:"bytes,5,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{9}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetAccountLabel() string {
	if m != nil {
		return m.AccountLabel
	}
	return ""
}

func (m *CreateRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *CreateRequest) GetPrivateAccount() *PrivateAccount {
	if m != nil {
		return m.PrivateAccount
	}
	return nil
}

func (m *CreateRequest) GetByAdmin() bool {
	if m != nil {
		return m.ByAdmin
	}
	return false
}

func (m *CreateRequest) GetAdminId() string {
	if m != nil {
		return m.AdminId
	}
	return ""
}

// CreateResponse is response after creating an account
type CreateResponse struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{10}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

// ActivateRequest is request to activate an account
type ActivateRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateRequest) Reset()         { *m = ActivateRequest{} }
func (m *ActivateRequest) String() string { return proto.CompactTextString(m) }
func (*ActivateRequest) ProtoMessage()    {}
func (*ActivateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{11}
}

func (m *ActivateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateRequest.Unmarshal(m, b)
}
func (m *ActivateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateRequest.Marshal(b, m, deterministic)
}
func (m *ActivateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateRequest.Merge(m, src)
}
func (m *ActivateRequest) XXX_Size() int {
	return xxx_messageInfo_ActivateRequest.Size(m)
}
func (m *ActivateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateRequest proto.InternalMessageInfo

func (m *ActivateRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *ActivateRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// ActivateResponse is response after activating an account
type ActivateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateResponse) Reset()         { *m = ActivateResponse{} }
func (m *ActivateResponse) String() string { return proto.CompactTextString(m) }
func (*ActivateResponse) ProtoMessage()    {}
func (*ActivateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{12}
}

func (m *ActivateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateResponse.Unmarshal(m, b)
}
func (m *ActivateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateResponse.Marshal(b, m, deterministic)
}
func (m *ActivateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateResponse.Merge(m, src)
}
func (m *ActivateResponse) XXX_Size() int {
	return xxx_messageInfo_ActivateResponse.Size(m)
}
func (m *ActivateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateResponse proto.InternalMessageInfo

// UpdateRequest is request to update an account
type UpdateRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Account              *Account `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{13}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *UpdateRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

// RequestChangePrivateAccountRequest is request to change private account
type RequestChangePrivateAccountRequest struct {
	Payload              string   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	FallbackUrl          string   `protobuf:"bytes,2,opt,name=fallback_url,json=fallbackUrl,proto3" json:"fallback_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestChangePrivateAccountRequest) Reset()         { *m = RequestChangePrivateAccountRequest{} }
func (m *RequestChangePrivateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*RequestChangePrivateAccountRequest) ProtoMessage()    {}
func (*RequestChangePrivateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{14}
}

func (m *RequestChangePrivateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestChangePrivateAccountRequest.Unmarshal(m, b)
}
func (m *RequestChangePrivateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestChangePrivateAccountRequest.Marshal(b, m, deterministic)
}
func (m *RequestChangePrivateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestChangePrivateAccountRequest.Merge(m, src)
}
func (m *RequestChangePrivateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_RequestChangePrivateAccountRequest.Size(m)
}
func (m *RequestChangePrivateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestChangePrivateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestChangePrivateAccountRequest proto.InternalMessageInfo

func (m *RequestChangePrivateAccountRequest) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *RequestChangePrivateAccountRequest) GetFallbackUrl() string {
	if m != nil {
		return m.FallbackUrl
	}
	return ""
}

// RequestChangePrivateAccountResponse is response after changing private account
type RequestChangePrivateAccountResponse struct {
	ResponseMessage      string   `protobuf:"bytes,1,opt,name=response_message,json=responseMessage,proto3" json:"response_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestChangePrivateAccountResponse) Reset()         { *m = RequestChangePrivateAccountResponse{} }
func (m *RequestChangePrivateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*RequestChangePrivateAccountResponse) ProtoMessage()    {}
func (*RequestChangePrivateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{15}
}

func (m *RequestChangePrivateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestChangePrivateAccountResponse.Unmarshal(m, b)
}
func (m *RequestChangePrivateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestChangePrivateAccountResponse.Marshal(b, m, deterministic)
}
func (m *RequestChangePrivateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestChangePrivateAccountResponse.Merge(m, src)
}
func (m *RequestChangePrivateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_RequestChangePrivateAccountResponse.Size(m)
}
func (m *RequestChangePrivateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestChangePrivateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestChangePrivateAccountResponse proto.InternalMessageInfo

func (m *RequestChangePrivateAccountResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

// UpdatePrivateRequest is request to update an account private information
type UpdatePrivateRequest struct {
	AccountId            string          `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	PrivateAccount       *PrivateAccount `protobuf:"bytes,2,opt,name=private_account,json=privateAccount,proto3" json:"private_account,omitempty"`
	ChangeToken          string          `protobuf:"bytes,3,opt,name=change_token,json=changeToken,proto3" json:"change_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdatePrivateRequest) Reset()         { *m = UpdatePrivateRequest{} }
func (m *UpdatePrivateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePrivateRequest) ProtoMessage()    {}
func (*UpdatePrivateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{16}
}

func (m *UpdatePrivateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePrivateRequest.Unmarshal(m, b)
}
func (m *UpdatePrivateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePrivateRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePrivateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePrivateRequest.Merge(m, src)
}
func (m *UpdatePrivateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePrivateRequest.Size(m)
}
func (m *UpdatePrivateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePrivateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePrivateRequest proto.InternalMessageInfo

func (m *UpdatePrivateRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *UpdatePrivateRequest) GetPrivateAccount() *PrivateAccount {
	if m != nil {
		return m.PrivateAccount
	}
	return nil
}

func (m *UpdatePrivateRequest) GetChangeToken() string {
	if m != nil {
		return m.ChangeToken
	}
	return ""
}

// DeleteRequest is request to delete an account
type DeleteRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{17}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

// GetRequest is request to retrieve account information
type GetRequest struct {
	AccountId            string      `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	View                 AccountView `protobuf:"varint,2,opt,name=view,proto3,enum=umrs.account.AccountView" json:"view,omitempty"`
	Privileged           bool        `protobuf:"varint,3,opt,name=privileged,proto3" json:"privileged,omitempty"`
	WithNationalId       bool        `protobuf:"varint,4,opt,name=with_national_id,json=withNationalId,proto3" json:"with_national_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{18}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *GetRequest) GetView() AccountView {
	if m != nil {
		return m.View
	}
	return AccountView_FULL_VIEW
}

func (m *GetRequest) GetPrivileged() bool {
	if m != nil {
		return m.Privileged
	}
	return false
}

func (m *GetRequest) GetWithNationalId() bool {
	if m != nil {
		return m.WithNationalId
	}
	return false
}

// ExistRequest is request to check if an account exists
type ExistRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	NationalId           string   `protobuf:"bytes,3,opt,name=national_id,json=nationalId,proto3" json:"national_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExistRequest) Reset()         { *m = ExistRequest{} }
func (m *ExistRequest) String() string { return proto.CompactTextString(m) }
func (*ExistRequest) ProtoMessage()    {}
func (*ExistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{19}
}

func (m *ExistRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExistRequest.Unmarshal(m, b)
}
func (m *ExistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExistRequest.Marshal(b, m, deterministic)
}
func (m *ExistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExistRequest.Merge(m, src)
}
func (m *ExistRequest) XXX_Size() int {
	return xxx_messageInfo_ExistRequest.Size(m)
}
func (m *ExistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExistRequest proto.InternalMessageInfo

func (m *ExistRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ExistRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ExistRequest) GetNationalId() string {
	if m != nil {
		return m.NationalId
	}
	return ""
}

// ExistResponse is response after checking whether account exist
type ExistResponse struct {
	Exists               bool     `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExistResponse) Reset()         { *m = ExistResponse{} }
func (m *ExistResponse) String() string { return proto.CompactTextString(m) }
func (*ExistResponse) ProtoMessage()    {}
func (*ExistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{20}
}

func (m *ExistResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExistResponse.Unmarshal(m, b)
}
func (m *ExistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExistResponse.Marshal(b, m, deterministic)
}
func (m *ExistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExistResponse.Merge(m, src)
}
func (m *ExistResponse) XXX_Size() int {
	return xxx_messageInfo_ExistResponse.Size(m)
}
func (m *ExistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExistResponse proto.InternalMessageInfo

func (m *ExistResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

// ChangeAccountType is request to change account type
type ChangeAccountTypeRequest struct {
	AccountId            string      `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	SuperAdminId         string      `protobuf:"bytes,2,opt,name=super_admin_id,json=superAdminId,proto3" json:"super_admin_id,omitempty"`
	Type                 AccountType `protobuf:"varint,3,opt,name=type,proto3,enum=umrs.account.AccountType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ChangeAccountTypeRequest) Reset()         { *m = ChangeAccountTypeRequest{} }
func (m *ChangeAccountTypeRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeAccountTypeRequest) ProtoMessage()    {}
func (*ChangeAccountTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{21}
}

func (m *ChangeAccountTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeAccountTypeRequest.Unmarshal(m, b)
}
func (m *ChangeAccountTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeAccountTypeRequest.Marshal(b, m, deterministic)
}
func (m *ChangeAccountTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeAccountTypeRequest.Merge(m, src)
}
func (m *ChangeAccountTypeRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeAccountTypeRequest.Size(m)
}
func (m *ChangeAccountTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeAccountTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeAccountTypeRequest proto.InternalMessageInfo

func (m *ChangeAccountTypeRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *ChangeAccountTypeRequest) GetSuperAdminId() string {
	if m != nil {
		return m.SuperAdminId
	}
	return ""
}

func (m *ChangeAccountTypeRequest) GetType() AccountType {
	if m != nil {
		return m.Type
	}
	return AccountType_ADMIN_VIEWER
}

// Accounts is a collection of user accounts
type Accounts struct {
	NextPageToken        int32      `protobuf:"varint,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	Accounts             []*Account `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Accounts) Reset()         { *m = Accounts{} }
func (m *Accounts) String() string { return proto.CompactTextString(m) }
func (*Accounts) ProtoMessage()    {}
func (*Accounts) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{22}
}

func (m *Accounts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Accounts.Unmarshal(m, b)
}
func (m *Accounts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Accounts.Marshal(b, m, deterministic)
}
func (m *Accounts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Accounts.Merge(m, src)
}
func (m *Accounts) XXX_Size() int {
	return xxx_messageInfo_Accounts.Size(m)
}
func (m *Accounts) XXX_DiscardUnknown() {
	xxx_messageInfo_Accounts.DiscardUnknown(m)
}

var xxx_messageInfo_Accounts proto.InternalMessageInfo

func (m *Accounts) GetNextPageToken() int32 {
	if m != nil {
		return m.NextPageToken
	}
	return 0
}

func (m *Accounts) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

// UndeleteRequest is request to undelete a deleted account
type UndeleteRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	SuperAdminId         string   `protobuf:"bytes,2,opt,name=super_admin_id,json=superAdminId,proto3" json:"super_admin_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UndeleteRequest) Reset()         { *m = UndeleteRequest{} }
func (m *UndeleteRequest) String() string { return proto.CompactTextString(m) }
func (*UndeleteRequest) ProtoMessage()    {}
func (*UndeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{23}
}

func (m *UndeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UndeleteRequest.Unmarshal(m, b)
}
func (m *UndeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UndeleteRequest.Marshal(b, m, deterministic)
}
func (m *UndeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UndeleteRequest.Merge(m, src)
}
func (m *UndeleteRequest) XXX_Size() int {
	return xxx_messageInfo_UndeleteRequest.Size(m)
}
func (m *UndeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UndeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UndeleteRequest proto.InternalMessageInfo

func (m *UndeleteRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *UndeleteRequest) GetSuperAdminId() string {
	if m != nil {
		return m.SuperAdminId
	}
	return ""
}

// ChangeAccountRequest is request to mutate an account type
type ChangeAccountRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	SuperAdminId         string   `protobuf:"bytes,2,opt,name=super_admin_id,json=superAdminId,proto3" json:"super_admin_id,omitempty"`
	Reason               string   `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeAccountRequest) Reset()         { *m = ChangeAccountRequest{} }
func (m *ChangeAccountRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeAccountRequest) ProtoMessage()    {}
func (*ChangeAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{24}
}

func (m *ChangeAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeAccountRequest.Unmarshal(m, b)
}
func (m *ChangeAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeAccountRequest.Marshal(b, m, deterministic)
}
func (m *ChangeAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeAccountRequest.Merge(m, src)
}
func (m *ChangeAccountRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeAccountRequest.Size(m)
}
func (m *ChangeAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeAccountRequest proto.InternalMessageInfo

func (m *ChangeAccountRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *ChangeAccountRequest) GetSuperAdminId() string {
	if m != nil {
		return m.SuperAdminId
	}
	return ""
}

func (m *ChangeAccountRequest) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

// Criteria contains filter criteria filtering colections of accounts
type Criteria struct {
	Filter               bool     `protobuf:"varint,1,opt,name=filter,proto3" json:"filter,omitempty"`
	ShowAdmins           bool     `protobuf:"varint,2,opt,name=show_admins,json=showAdmins,proto3" json:"show_admins,omitempty"`
	ShowUsers            bool     `protobuf:"varint,3,opt,name=show_users,json=showUsers,proto3" json:"show_users,omitempty"`
	ShowActiveAccounts   bool     `protobuf:"varint,4,opt,name=show_active_accounts,json=showActiveAccounts,proto3" json:"show_active_accounts,omitempty"`
	ShowInactiveAccounts bool     `protobuf:"varint,5,opt,name=show_inactive_accounts,json=showInactiveAccounts,proto3" json:"show_inactive_accounts,omitempty"`
	ShowBlockedAccounts  bool     `protobuf:"varint,6,opt,name=show_blocked_accounts,json=showBlockedAccounts,proto3" json:"show_blocked_accounts,omitempty"`
	ShowMales            bool     `protobuf:"varint,7,opt,name=show_males,json=showMales,proto3" json:"show_males,omitempty"`
	ShowFemales          bool     `protobuf:"varint,8,opt,name=show_females,json=showFemales,proto3" json:"show_females,omitempty"`
	FilterCreationDate   bool     `protobuf:"varint,9,opt,name=filter_creation_date,json=filterCreationDate,proto3" json:"filter_creation_date,omitempty"`
	CreatedFrom          int64    `protobuf:"varint,10,opt,name=created_from,json=createdFrom,proto3" json:"created_from,omitempty"`
	CreatedUntil         int64    `protobuf:"varint,11,opt,name=created_until,json=createdUntil,proto3" json:"created_until,omitempty"`
	FilterAccountLabels  bool     `protobuf:"varint,12,opt,name=filter_account_labels,json=filterAccountLabels,proto3" json:"filter_account_labels,omitempty"`
	Labels               []string `protobuf:"bytes,13,rep,name=labels,proto3" json:"labels,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Criteria) Reset()         { *m = Criteria{} }
func (m *Criteria) String() string { return proto.CompactTextString(m) }
func (*Criteria) ProtoMessage()    {}
func (*Criteria) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{25}
}

func (m *Criteria) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Criteria.Unmarshal(m, b)
}
func (m *Criteria) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Criteria.Marshal(b, m, deterministic)
}
func (m *Criteria) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Criteria.Merge(m, src)
}
func (m *Criteria) XXX_Size() int {
	return xxx_messageInfo_Criteria.Size(m)
}
func (m *Criteria) XXX_DiscardUnknown() {
	xxx_messageInfo_Criteria.DiscardUnknown(m)
}

var xxx_messageInfo_Criteria proto.InternalMessageInfo

func (m *Criteria) GetFilter() bool {
	if m != nil {
		return m.Filter
	}
	return false
}

func (m *Criteria) GetShowAdmins() bool {
	if m != nil {
		return m.ShowAdmins
	}
	return false
}

func (m *Criteria) GetShowUsers() bool {
	if m != nil {
		return m.ShowUsers
	}
	return false
}

func (m *Criteria) GetShowActiveAccounts() bool {
	if m != nil {
		return m.ShowActiveAccounts
	}
	return false
}

func (m *Criteria) GetShowInactiveAccounts() bool {
	if m != nil {
		return m.ShowInactiveAccounts
	}
	return false
}

func (m *Criteria) GetShowBlockedAccounts() bool {
	if m != nil {
		return m.ShowBlockedAccounts
	}
	return false
}

func (m *Criteria) GetShowMales() bool {
	if m != nil {
		return m.ShowMales
	}
	return false
}

func (m *Criteria) GetShowFemales() bool {
	if m != nil {
		return m.ShowFemales
	}
	return false
}

func (m *Criteria) GetFilterCreationDate() bool {
	if m != nil {
		return m.FilterCreationDate
	}
	return false
}

func (m *Criteria) GetCreatedFrom() int64 {
	if m != nil {
		return m.CreatedFrom
	}
	return 0
}

func (m *Criteria) GetCreatedUntil() int64 {
	if m != nil {
		return m.CreatedUntil
	}
	return 0
}

func (m *Criteria) GetFilterAccountLabels() bool {
	if m != nil {
		return m.FilterAccountLabels
	}
	return false
}

func (m *Criteria) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

// ListAccountsRequest is request to retrieve collection of accounts
type ListAccountsRequest struct {
	PageToken            int32       `protobuf:"varint,1,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize             int32       `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	ListCriteria         *Criteria   `protobuf:"bytes,3,opt,name=list_criteria,json=listCriteria,proto3" json:"list_criteria,omitempty"`
	View                 AccountView `protobuf:"varint,4,opt,name=view,proto3,enum=umrs.account.AccountView" json:"view,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListAccountsRequest) Reset()         { *m = ListAccountsRequest{} }
func (m *ListAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAccountsRequest) ProtoMessage()    {}
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{26}
}

func (m *ListAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsRequest.Unmarshal(m, b)
}
func (m *ListAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsRequest.Marshal(b, m, deterministic)
}
func (m *ListAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsRequest.Merge(m, src)
}
func (m *ListAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAccountsRequest.Size(m)
}
func (m *ListAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsRequest proto.InternalMessageInfo

func (m *ListAccountsRequest) GetPageToken() int32 {
	if m != nil {
		return m.PageToken
	}
	return 0
}

func (m *ListAccountsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListAccountsRequest) GetListCriteria() *Criteria {
	if m != nil {
		return m.ListCriteria
	}
	return nil
}

func (m *ListAccountsRequest) GetView() AccountView {
	if m != nil {
		return m.View
	}
	return AccountView_FULL_VIEW
}

// SearchAccountsRequest is request to search for accounts
type SearchAccountsRequest struct {
	PageToken            int32       `protobuf:"varint,1,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize             int32       `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SearchCriteria       *Criteria   `protobuf:"bytes,3,opt,name=search_criteria,json=searchCriteria,proto3" json:"search_criteria,omitempty"`
	Query                string      `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	View                 AccountView `protobuf:"varint,5,opt,name=view,proto3,enum=umrs.account.AccountView" json:"view,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SearchAccountsRequest) Reset()         { *m = SearchAccountsRequest{} }
func (m *SearchAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*SearchAccountsRequest) ProtoMessage()    {}
func (*SearchAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{27}
}

func (m *SearchAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchAccountsRequest.Unmarshal(m, b)
}
func (m *SearchAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchAccountsRequest.Marshal(b, m, deterministic)
}
func (m *SearchAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchAccountsRequest.Merge(m, src)
}
func (m *SearchAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_SearchAccountsRequest.Size(m)
}
func (m *SearchAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchAccountsRequest proto.InternalMessageInfo

func (m *SearchAccountsRequest) GetPageToken() int32 {
	if m != nil {
		return m.PageToken
	}
	return 0
}

func (m *SearchAccountsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *SearchAccountsRequest) GetSearchCriteria() *Criteria {
	if m != nil {
		return m.SearchCriteria
	}
	return nil
}

func (m *SearchAccountsRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchAccountsRequest) GetView() AccountView {
	if m != nil {
		return m.View
	}
	return AccountView_FULL_VIEW
}

func init() {
	proto.RegisterEnum("umrs.account.AccountType", AccountType_name, AccountType_value)
	proto.RegisterEnum("umrs.account.AccountState", AccountState_name, AccountState_value)
	proto.RegisterEnum("umrs.account.AccountView", AccountView_name, AccountView_value)
	proto.RegisterType((*Account)(nil), "umrs.account.Account")
	proto.RegisterType((*PrivateAccount)(nil), "umrs.account.PrivateAccount")
	proto.RegisterType((*SocialProfile)(nil), "umrs.account.SocialProfile")
	proto.RegisterType((*Google)(nil), "umrs.account.Google")
	proto.RegisterType((*Facebook)(nil), "umrs.account.Facebook")
	proto.RegisterType((*Twitter)(nil), "umrs.account.Twitter")
	proto.RegisterType((*Creds)(nil), "umrs.account.Creds")
	proto.RegisterType((*LoginRequest)(nil), "umrs.account.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "umrs.account.LoginResponse")
	proto.RegisterType((*CreateRequest)(nil), "umrs.account.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "umrs.account.CreateResponse")
	proto.RegisterType((*ActivateRequest)(nil), "umrs.account.ActivateRequest")
	proto.RegisterType((*ActivateResponse)(nil), "umrs.account.ActivateResponse")
	proto.RegisterType((*UpdateRequest)(nil), "umrs.account.UpdateRequest")
	proto.RegisterType((*RequestChangePrivateAccountRequest)(nil), "umrs.account.RequestChangePrivateAccountRequest")
	proto.RegisterType((*RequestChangePrivateAccountResponse)(nil), "umrs.account.RequestChangePrivateAccountResponse")
	proto.RegisterType((*UpdatePrivateRequest)(nil), "umrs.account.UpdatePrivateRequest")
	proto.RegisterType((*DeleteRequest)(nil), "umrs.account.DeleteRequest")
	proto.RegisterType((*GetRequest)(nil), "umrs.account.GetRequest")
	proto.RegisterType((*ExistRequest)(nil), "umrs.account.ExistRequest")
	proto.RegisterType((*ExistResponse)(nil), "umrs.account.ExistResponse")
	proto.RegisterType((*ChangeAccountTypeRequest)(nil), "umrs.account.ChangeAccountTypeRequest")
	proto.RegisterType((*Accounts)(nil), "umrs.account.Accounts")
	proto.RegisterType((*UndeleteRequest)(nil), "umrs.account.UndeleteRequest")
	proto.RegisterType((*ChangeAccountRequest)(nil), "umrs.account.ChangeAccountRequest")
	proto.RegisterType((*Criteria)(nil), "umrs.account.Criteria")
	proto.RegisterType((*ListAccountsRequest)(nil), "umrs.account.ListAccountsRequest")
	proto.RegisterType((*SearchAccountsRequest)(nil), "umrs.account.SearchAccountsRequest")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 2170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0x4b, 0x73, 0xdb, 0xc8,
	0x11, 0x16, 0x48, 0xf1, 0xd5, 0x7c, 0x7a, 0x2c, 0xab, 0x68, 0xca, 0x0f, 0x19, 0xf2, 0xda, 0x5a,
	0xad, 0x2d, 0xad, 0x15, 0xe7, 0xe2, 0xa4, 0x6a, 0x8b, 0x92, 0x28, 0x8b, 0x15, 0x59, 0x56, 0x20,
	0xc9, 0x5b, 0x95, 0x1c, 0x50, 0x20, 0x39, 0xa4, 0x10, 0x83, 0x00, 0x0c, 0x80, 0xd6, 0x72, 0x53,
	0x5b, 0xa9, 0xca, 0x21, 0xc7, 0x5c, 0xf2, 0x03, 0x72, 0xc9, 0x35, 0x87, 0x54, 0xce, 0xc9, 0x9f,
	0xc8, 0x29, 0xd7, 0x54, 0x2e, 0xa9, 0x1c, 0xf3, 0x07, 0x52, 0xd3, 0x33, 0x03, 0x02, 0x10, 0x29,
	0x51, 0x89, 0xf7, 0x44, 0xf6, 0x6b, 0xbe, 0xee, 0x9e, 0x9e, 0x9e, 0x1e, 0x40, 0xd9, 0xe8, 0x76,
	0x9d, 0x91, 0x1d, 0x6c, 0xba, 0x9e, 0x13, 0x38, 0xa4, 0x34, 0xec, 0xf6, 0xdd, 0x4d, 0xc1, 0x6b,
	0xac, 0x0c, 0x1c, 0x67, 0x60, 0xd1, 0x2d, 0x94, 0x75, 0x46, 0xfd, 0x2d, 0x3a, 0x74, 0x83, 0x31,
	0x57, 0x6d, 0xdc, 0x13, 0x42, 0xc3, 0x35, 0xb7, 0x0c, 0xdb, 0x76, 0x02, 0x23, 0x30, 0x1d, 0xdb,
	0x17, 0xd2, 0x67, 0xf8, 0xd3, 0x7d, 0x3e, 0xa0, 0xf6, 0x73, 0xff, 0xc2, 0x18, 0x0c, 0xa8, 0xb7,
	0xe5, 0xb8, 0xa8, 0x71, 0x59, 0x5b, 0xfd, 0xf3, 0x22, 0xe4, 0x9a, 0x1c, 0x94, 0xdc, 0x07, 0x10,
	0xf8, 0xba, 0xd9, 0xab, 0x2b, 0xab, 0xca, 0x7a, 0x41, 0x2b, 0x08, 0x4e, 0xbb, 0x47, 0x1e, 0x42,
	0xd1, 0x46, 0x5b, 0xc3, 0x62, 0xf2, 0x14, 0xca, 0x41, 0xb2, 0xda, 0x3d, 0xb2, 0x04, 0x19, 0x3a,
	0x34, 0x4c, 0xab, 0x9e, 0x46, 0x11, 0x27, 0x18, 0xd7, 0x3d, 0x77, 0x6c, 0x5a, 0x5f, 0xe4, 0x5c,
	0x24, 0x18, 0x56, 0xdf, 0xf4, 0xfc, 0x40, 0xb7, 0x8d, 0x21, 0xad, 0x67, 0x38, 0x16, 0x72, 0x8e,
	0x8c, 0x21, 0x25, 0x2b, 0x50, 0xb0, 0x0c, 0x29, 0xcd, 0xa2, 0x34, 0xcf, 0x18, 0x28, 0xbc, 0x0f,
	0xd0, 0x31, 0xbd, 0xe0, 0x5c, 0xef, 0x19, 0x01, 0xad, 0xe7, 0xb8, 0x2d, 0x72, 0xf6, 0x8c, 0x80,
	0x92, 0x65, 0xc8, 0x0e, 0xa8, 0xdd, 0xa3, 0x5e, 0x3d, 0x8f, 0x22, 0x41, 0x91, 0xd5, 0x89, 0xff,
	0x66, 0x30, 0xae, 0x17, 0x50, 0x18, 0x65, 0x91, 0x0d, 0xb8, 0xe5, 0x7a, 0x4e, 0xdf, 0xb4, 0xa8,
	0x3e, 0xf2, 0x2c, 0x3d, 0x38, 0x1f, 0x0d, 0x3b, 0x75, 0x40, 0xbd, 0xaa, 0x10, 0x9c, 0x79, 0xd6,
	0x29, 0x63, 0x93, 0x67, 0x40, 0xa2, 0xba, 0xb6, 0xe3, 0x0d, 0x0d, 0xab, 0x5e, 0x44, 0xe5, 0xda,
	0x44, 0xf9, 0x08, 0xf9, 0xe4, 0xc7, 0x50, 0x92, 0xa9, 0x0d, 0xc6, 0x2e, 0xad, 0x97, 0x56, 0x95,
	0xf5, 0xca, 0xf6, 0xdd, 0xcd, 0xe8, 0xa6, 0x6f, 0x8a, 0x7d, 0x38, 0x1d, 0xbb, 0x54, 0x2b, 0x1a,
	0x13, 0x82, 0x7c, 0x15, 0x16, 0x8b, 0xee, 0x07, 0x2c, 0xe6, 0x32, 0x9a, 0x37, 0xa6, 0x9a, 0x9f,
	0x30, 0x0d, 0x4d, 0xc2, 0x21, 0x45, 0x3e, 0x83, 0x8a, 0x5c, 0xc0, 0x32, 0x3a, 0xd4, 0xf2, 0xeb,
	0x95, 0xd5, 0xf4, 0x7a, 0x41, 0x93, 0xcb, 0x1e, 0x22, 0x93, 0x3c, 0x85, 0x6a, 0xe0, 0x8d, 0xfc,
	0x80, 0xf6, 0xf4, 0x1e, 0xfd, 0x68, 0x76, 0xa9, 0x5f, 0xaf, 0xa2, 0x5e, 0x45, 0xb0, 0xf7, 0x38,
	0x57, 0xfd, 0xa3, 0x02, 0x95, 0x63, 0xcf, 0xfc, 0x68, 0x04, 0x54, 0x16, 0x4f, 0x03, 0xf2, 0xae,
	0xe1, 0xfb, 0x17, 0x8e, 0x27, 0x4b, 0x27, 0xa4, 0xc9, 0xe7, 0x50, 0xeb, 0x3a, 0x76, 0xdf, 0xf4,
	0x86, 0x7a, 0xa8, 0xc3, 0xcb, 0xa7, 0x2a, 0xf8, 0xc7, 0x52, 0xf5, 0x0b, 0xb8, 0xe5, 0xd3, 0xee,
	0xc8, 0x33, 0x83, 0xb1, 0xfe, 0x61, 0x44, 0x7d, 0xb6, 0x39, 0xa2, 0x9e, 0x6a, 0x52, 0xf0, 0x53,
	0xc1, 0x67, 0xfe, 0x86, 0xca, 0x86, 0xed, 0x5f, 0x50, 0x4f, 0x14, 0x59, 0x45, 0xb2, 0x9b, 0xc8,
	0x55, 0xff, 0xad, 0x40, 0xf9, 0xc4, 0xe9, 0x9a, 0x86, 0x75, 0xcc, 0x77, 0x26, 0x51, 0x7f, 0xca,
	0x95, 0xf5, 0x97, 0x4a, 0xd4, 0xdf, 0x23, 0x28, 0x61, 0x11, 0xeb, 0xf6, 0x68, 0xd8, 0xa1, 0x9e,
	0x70, 0xaf, 0x88, 0xbc, 0x23, 0x64, 0x91, 0x35, 0x28, 0x63, 0xf5, 0xeb, 0x46, 0xaf, 0xe7, 0x51,
	0xdf, 0x17, 0x7e, 0x95, 0x90, 0xd9, 0xe4, 0x3c, 0x76, 0xa0, 0x22, 0x25, 0x24, 0x0e, 0x01, 0x4c,
	0x6a, 0x27, 0x52, 0xc9, 0xd9, 0x58, 0x25, 0x5f, 0x7d, 0x00, 0xd4, 0x43, 0xc8, 0xbe, 0xc6, 0x0e,
	0x41, 0x76, 0xa0, 0xc2, 0x7b, 0x85, 0x2e, 0x56, 0xc5, 0x48, 0x8b, 0xdb, 0x2b, 0xf1, 0xca, 0x89,
	0xa5, 0x46, 0x2b, 0x73, 0x13, 0x41, 0xaa, 0xfb, 0x90, 0xdf, 0x37, 0xba, 0xb4, 0xe3, 0x38, 0xef,
	0xc9, 0x2b, 0x80, 0x7e, 0xe7, 0x26, 0x6b, 0x15, 0xfa, 0x1d, 0xb9, 0xce, 0x5b, 0xc8, 0x9d, 0x5e,
	0x98, 0x41, 0x40, 0x3d, 0xb2, 0x07, 0xd5, 0x80, 0xff, 0xbd, 0xc9, 0x5a, 0x15, 0x61, 0x23, 0x17,
	0x74, 0x21, 0xb3, 0xeb, 0xd1, 0x9e, 0x3f, 0xe9, 0x30, 0x4a, 0xb4, 0xc3, 0x84, 0xdd, 0x28, 0x15,
	0xed, 0x46, 0x89, 0x26, 0x96, 0xbe, 0xd4, 0xc4, 0xa2, 0x75, 0xbc, 0x18, 0xaf, 0x63, 0xf5, 0x3f,
	0x0a, 0x94, 0x0e, 0x9d, 0x81, 0x69, 0x6b, 0x14, 0x6b, 0x93, 0xbc, 0x84, 0x7c, 0x5f, 0xe4, 0x46,
	0x44, 0xb0, 0x1c, 0x8f, 0x40, 0x66, 0xee, 0x60, 0x41, 0x0b, 0x35, 0xc9, 0x26, 0x64, 0x79, 0x8a,
	0xd1, 0xb5, 0xe2, 0xf6, 0x52, 0xdc, 0x86, 0xef, 0xdd, 0xc1, 0x82, 0x26, 0xb4, 0xc8, 0x0b, 0xc8,
	0x89, 0xd0, 0xd1, 0xdf, 0xe2, 0xf6, 0x9d, 0xb8, 0x81, 0x48, 0xeb, 0xc1, 0x82, 0x26, 0xf5, 0xc8,
	0x17, 0x90, 0xe9, 0xb2, 0xdc, 0x60, 0x08, 0xc5, 0xed, 0xdb, 0x71, 0x03, 0x4c, 0xdb, 0xc1, 0x82,
	0xc6, 0x75, 0x58, 0xa6, 0x06, 0x9e, 0x33, 0x72, 0x45, 0x05, 0x72, 0x62, 0x27, 0x07, 0x19, 0x8b,
	0xc5, 0xaa, 0xfe, 0x49, 0x81, 0xb2, 0x88, 0xda, 0x77, 0x1d, 0xdb, 0xc7, 0xd4, 0x06, 0xce, 0x7b,
	0x6a, 0xcb, 0x84, 0x23, 0x91, 0xb8, 0x3e, 0x52, 0xc9, 0xeb, 0x63, 0x2d, 0xd9, 0xc4, 0x78, 0xee,
	0xe3, 0x8d, 0xea, 0x51, 0xa2, 0x4f, 0xf2, 0x1d, 0x88, 0x35, 0xc3, 0xc8, 0x3a, 0x51, 0xaf, 0xa5,
	0xdd, 0x6b, 0xc6, 0x53, 0xff, 0xa1, 0x40, 0x79, 0xd7, 0xa3, 0xac, 0x13, 0x8a, 0xad, 0x8a, 0x98,
	0x61, 0x0b, 0x14, 0xbe, 0x97, 0xa2, 0x1d, 0x90, 0x6c, 0x41, 0x4e, 0xd0, 0x62, 0x6b, 0xee, 0x4c,
	0x6d, 0xb1, 0x9a, 0xd4, 0x22, 0x2d, 0xa8, 0xba, 0xbc, 0x0f, 0xea, 0xd2, 0x90, 0x6f, 0xd1, 0xbd,
	0xb8, 0x61, 0xbc, 0x59, 0x6a, 0x15, 0x37, 0xde, 0x3c, 0xef, 0x42, 0xbe, 0x33, 0xd6, 0x8d, 0xde,
	0xd0, 0xb4, 0x31, 0xe4, 0xbc, 0x96, 0xeb, 0x8c, 0x9b, 0x8c, 0x64, 0x22, 0xe4, 0xb3, 0x9c, 0xf2,
	0x48, 0x73, 0x48, 0xb7, 0x7b, 0xea, 0x16, 0x54, 0x64, 0x8c, 0x62, 0x63, 0xae, 0xbe, 0xc1, 0xd5,
	0x7d, 0xa8, 0x36, 0xbb, 0x01, 0x22, 0xcb, 0xb4, 0x5c, 0x73, 0xe7, 0x87, 0x3b, 0x9d, 0x8a, 0xec,
	0xb4, 0x4a, 0xa0, 0x36, 0x59, 0x87, 0x43, 0xab, 0x3a, 0x94, 0xcf, 0xdc, 0xde, 0xfc, 0x2b, 0xdf,
	0x34, 0xd5, 0xaa, 0x01, 0xaa, 0x58, 0x7a, 0xf7, 0xdc, 0xb0, 0x07, 0x34, 0x91, 0x52, 0x81, 0x5a,
	0x87, 0x9c, 0x6b, 0x8c, 0x2d, 0xc7, 0x90, 0x90, 0x92, 0x64, 0xa5, 0xd5, 0x37, 0x2c, 0xab, 0x63,
	0x74, 0xdf, 0x63, 0xbb, 0xe5, 0x11, 0x15, 0x25, 0xef, 0xcc, 0xb3, 0xd4, 0x63, 0x58, 0xbb, 0x12,
	0x42, 0x64, 0xf9, 0x73, 0xa8, 0x79, 0xe2, 0xbf, 0x3e, 0xa4, 0xbe, 0x6f, 0x0c, 0x64, 0xeb, 0xa9,
	0x4a, 0xfe, 0x1b, 0xce, 0x56, 0x7f, 0xaf, 0xc0, 0x12, 0x4f, 0x8b, 0x58, 0x6b, 0xce, 0xec, 0x4c,
	0xa9, 0xab, 0xd4, 0xff, 0x50, 0x57, 0x8f, 0xa0, 0xd4, 0xc5, 0x48, 0x74, 0xbe, 0x8b, 0xe2, 0xa6,
	0xe2, 0xbc, 0x53, 0xdc, 0xcb, 0x4d, 0x28, 0xef, 0x51, 0x8b, 0xce, 0xeb, 0x99, 0xfa, 0x07, 0x05,
	0xe0, 0x35, 0x0d, 0xe6, 0x8c, 0xe3, 0x39, 0x2c, 0x7e, 0x34, 0xe9, 0x05, 0x3a, 0x3f, 0x6b, 0xde,
	0x79, 0x67, 0xd2, 0x0b, 0x0d, 0xd5, 0xc8, 0x03, 0x00, 0x16, 0x81, 0x69, 0xd1, 0x01, 0xe5, 0xcd,
	0x39, 0xaf, 0x45, 0x38, 0x64, 0x1d, 0x6a, 0x17, 0x66, 0x70, 0xae, 0x47, 0x5b, 0x38, 0x3f, 0x2f,
	0x15, 0xc6, 0x3f, 0x0a, 0xdb, 0xb8, 0xfa, 0x73, 0x28, 0xb5, 0xbe, 0x31, 0xfd, 0xd0, 0xcf, 0xf0,
	0x36, 0x50, 0xa6, 0xce, 0xa6, 0xa9, 0xe8, 0xcd, 0x71, 0xdd, 0x1d, 0xa1, 0x3e, 0x85, 0xb2, 0x58,
	0x5c, 0x54, 0xc4, 0x32, 0x64, 0x29, 0x63, 0xf8, 0xb8, 0x7c, 0x5e, 0x13, 0x94, 0xfa, 0x5b, 0x05,
	0xea, 0xbc, 0x94, 0xa2, 0xb3, 0xdd, 0x7c, 0xa9, 0x7b, 0x0c, 0x15, 0x7f, 0xe4, 0x52, 0x4f, 0x0f,
	0x8f, 0x3f, 0x77, 0xb2, 0x84, 0xdc, 0x26, 0xef, 0x01, 0x2c, 0xc1, 0xd8, 0x28, 0xd3, 0xd7, 0x0d,
	0x94, 0xa8, 0xa6, 0x52, 0xc8, 0x0b, 0xa6, 0x4f, 0x9e, 0x40, 0xd5, 0xa6, 0xdf, 0x04, 0xba, 0x6b,
	0x84, 0xf5, 0xc1, 0x9c, 0xc8, 0x68, 0x65, 0xc6, 0x3e, 0x36, 0x44, 0x85, 0x90, 0x17, 0x90, 0x17,
	0x0b, 0xfa, 0xf5, 0xd4, 0x6a, 0x7a, 0xf6, 0x51, 0x0d, 0xd5, 0xd4, 0x77, 0x50, 0x3d, 0xb3, 0x7b,
	0x37, 0x28, 0xab, 0xf9, 0xa2, 0x55, 0x7d, 0x58, 0x8a, 0xa5, 0xf3, 0x93, 0xa6, 0x72, 0x19, 0xb2,
	0x1e, 0x35, 0xfc, 0x70, 0xde, 0x14, 0x94, 0xfa, 0x9b, 0x45, 0xc8, 0xef, 0x7a, 0x66, 0x40, 0x3d,
	0xd3, 0x60, 0x4a, 0x7d, 0xd3, 0x62, 0x57, 0xb1, 0xd8, 0x69, 0x4e, 0xb1, 0x9a, 0xf1, 0xcf, 0x9d,
	0x0b, 0x8e, 0xe0, 0xe3, 0xfa, 0x79, 0x0d, 0x18, 0x0b, 0x97, 0xf7, 0x99, 0x8b, 0xa8, 0x30, 0xf2,
	0xa9, 0xe7, 0x8b, 0xd2, 0x2e, 0x30, 0xce, 0x19, 0x63, 0x90, 0x2f, 0x61, 0x89, 0xdb, 0xb3, 0xbe,
	0x1a, 0x1e, 0x7a, 0x5f, 0x54, 0x37, 0xc1, 0x85, 0x50, 0x14, 0x6e, 0xdf, 0x4b, 0x58, 0x46, 0x0b,
	0xd3, 0x4e, 0xda, 0x64, 0xd0, 0x06, 0xd7, 0x6b, 0x0b, 0x61, 0x68, 0xb5, 0x0d, 0x77, 0xd0, 0xaa,
	0x63, 0x39, 0xdd, 0xf7, 0xb4, 0x37, 0x31, 0xca, 0xa2, 0xd1, 0x6d, 0x26, 0xdc, 0xe1, 0xb2, 0xd0,
	0x46, 0xba, 0x3e, 0x34, 0x2c, 0xea, 0xe3, 0xb8, 0x29, 0x5c, 0x7f, 0xc3, 0x18, 0xac, 0xc9, 0xa0,
	0xb8, 0x4f, 0xb9, 0x42, 0x1e, 0x15, 0x30, 0x1d, 0xfb, 0x9c, 0xc5, 0xa2, 0xe3, 0x79, 0xd2, 0xbb,
	0xec, 0xc2, 0x32, 0x1d, 0x9b, 0x8f, 0xae, 0x05, 0x1e, 0x1d, 0x97, 0xed, 0x0a, 0xd1, 0x9e, 0x18,
	0x04, 0x50, 0x95, 0xf6, 0xf4, 0xbe, 0xe7, 0x0c, 0xf1, 0x15, 0x96, 0xd6, 0x8a, 0x82, 0xb7, 0xef,
	0x39, 0x43, 0x76, 0xa3, 0x4b, 0x95, 0x91, 0x1d, 0x98, 0xfc, 0xf1, 0x95, 0xd6, 0xa4, 0xdd, 0x19,
	0xe3, 0xb1, 0x78, 0x05, 0x72, 0xe2, 0x01, 0x54, 0xe2, 0xf1, 0x72, 0x61, 0x33, 0xf6, 0x0c, 0x5a,
	0x86, 0xac, 0x50, 0x2a, 0xe3, 0xeb, 0x47, 0x50, 0xea, 0x5f, 0x14, 0xb8, 0x7d, 0x68, 0xfa, 0x81,
	0x4c, 0x4c, 0xa4, 0xfa, 0x2e, 0x9d, 0xa1, 0x82, 0x1b, 0x9e, 0x9f, 0x15, 0x40, 0x42, 0xf7, 0xcd,
	0x6f, 0x79, 0xa3, 0xc9, 0xb0, 0x91, 0x72, 0x40, 0x4f, 0xcc, 0x6f, 0x29, 0xf9, 0x11, 0x94, 0x2d,
	0xd3, 0x0f, 0xf4, 0xae, 0x28, 0x30, 0x31, 0x3e, 0x2c, 0x27, 0x07, 0x36, 0x2e, 0xd5, 0x4a, 0x4c,
	0x39, 0x2c, 0x46, 0xd9, 0x5d, 0x17, 0xe7, 0xea, 0xae, 0xea, 0xdf, 0x15, 0xb8, 0x73, 0x42, 0x0d,
	0xaf, 0x7b, 0xfe, 0x29, 0x23, 0xf8, 0x8a, 0x3d, 0xc2, 0xd8, 0xa2, 0xf3, 0xc6, 0x50, 0xe1, 0xea,
	0x61, 0x14, 0x4b, 0x90, 0xf9, 0x30, 0xa2, 0xde, 0x58, 0x7e, 0x20, 0x40, 0x22, 0x8c, 0x2d, 0x33,
	0x57, 0x6c, 0x1b, 0x1a, 0x14, 0x23, 0xdd, 0x8e, 0xd4, 0xa0, 0xd4, 0xdc, 0x7b, 0xd3, 0x3e, 0xd2,
	0xdf, 0xb5, 0x5b, 0x5f, 0xb7, 0xb4, 0xda, 0x02, 0xa9, 0x42, 0x91, 0x73, 0xde, 0x7e, 0x7d, 0xd4,
	0xd2, 0x6a, 0xca, 0x44, 0xa5, 0xb5, 0xd7, 0x3e, 0x7d, 0xab, 0xd5, 0x52, 0xa4, 0x02, 0x70, 0x76,
	0xd2, 0xd2, 0x84, 0x46, 0x7a, 0xe3, 0x87, 0x50, 0x8a, 0xbe, 0xa9, 0x49, 0x11, 0x72, 0x3b, 0x87,
	0x6f, 0x77, 0x7f, 0xd2, 0xda, 0xab, 0x2d, 0x10, 0x80, 0x6c, 0x73, 0xf7, 0xb4, 0xfd, 0xae, 0x55,
	0x53, 0x48, 0x09, 0xf2, 0xed, 0x23, 0x41, 0xa5, 0x36, 0x0e, 0x43, 0x57, 0x98, 0x7f, 0xa4, 0x0c,
	0x85, 0xfd, 0xb3, 0xc3, 0x43, 0xf4, 0xa4, 0xb6, 0xc0, 0xc8, 0xc3, 0xf6, 0xc9, 0x29, 0x27, 0x15,
	0xe6, 0xd6, 0x49, 0xab, 0xa9, 0xed, 0x1e, 0x70, 0x06, 0x3a, 0xb1, 0xd3, 0x3c, 0x69, 0xef, 0x72,
	0x3a, 0xbd, 0xfd, 0xaf, 0x0a, 0x80, 0x58, 0xae, 0x79, 0xdc, 0x26, 0x14, 0x32, 0x38, 0x8b, 0x93,
	0xc4, 0xe3, 0x3f, 0xfa, 0x2c, 0x69, 0xac, 0x4c, 0x95, 0x89, 0x41, 0x6d, 0xed, 0xd7, 0x7f, 0xfb,
	0xe7, 0xef, 0x52, 0xf7, 0xd5, 0x3a, 0x7e, 0x3f, 0x62, 0x8a, 0x5b, 0xb2, 0x09, 0x6c, 0xe1, 0xc0,
	0xff, 0x4a, 0xd9, 0x20, 0x26, 0x64, 0xf9, 0x68, 0x49, 0x56, 0x2e, 0x3d, 0x1d, 0x26, 0x53, 0x4c,
	0xe3, 0xde, 0x74, 0xa1, 0x40, 0x7a, 0x8c, 0x48, 0x0f, 0xd4, 0xbb, 0x53, 0x90, 0xf8, 0x21, 0x65,
	0x50, 0x23, 0x76, 0x25, 0xf1, 0x61, 0x92, 0xdc, 0x4f, 0x6e, 0x73, 0x6c, 0x58, 0x6d, 0x3c, 0x98,
	0x25, 0x16, 0x80, 0x1b, 0x08, 0xf8, 0x98, 0xa8, 0x53, 0x00, 0x59, 0x1f, 0x74, 0x6c, 0xfc, 0x41,
	0x28, 0x13, 0xb2, 0x7c, 0x30, 0x4b, 0x46, 0x18, 0x9b, 0x62, 0x1b, 0xcb, 0x9b, 0xfc, 0x11, 0xb6,
	0x29, 0xbf, 0xc4, 0x6d, 0xb6, 0x86, 0x6e, 0x30, 0x96, 0x50, 0x8d, 0x87, 0x53, 0xa0, 0x7e, 0x39,
	0xb9, 0x8b, 0xbe, 0x63, 0x11, 0xfe, 0x4a, 0x8e, 0xc6, 0x62, 0x5a, 0x23, 0xea, 0x34, 0xc4, 0xf8,
	0x80, 0x38, 0x13, 0x78, 0x1b, 0x81, 0x9f, 0x35, 0x9e, 0x5e, 0x03, 0xbc, 0x25, 0x46, 0x41, 0xe6,
	0x40, 0x1f, 0xb2, 0x7c, 0xc6, 0x4b, 0xc6, 0x1a, 0x9b, 0xfc, 0x66, 0x42, 0x3e, 0x45, 0xc8, 0x47,
	0x1b, 0xd7, 0xc5, 0x4a, 0x74, 0x48, 0xbf, 0xa6, 0x01, 0xa9, 0x27, 0xde, 0xb3, 0xe1, 0xb4, 0xd8,
	0x98, 0x3e, 0x38, 0x48, 0x00, 0x72, 0x2d, 0xc0, 0x2f, 0x20, 0x83, 0x83, 0x57, 0xb2, 0xfa, 0xa3,
	0xa3, 0x5e, 0xb2, 0xfa, 0x63, 0x93, 0x9a, 0xba, 0x8e, 0x50, 0x2a, 0x59, 0x9d, 0x5d, 0x22, 0x7c,
	0x76, 0x23, 0x7f, 0x55, 0x60, 0xe5, 0x8a, 0xd7, 0x00, 0xf9, 0x32, 0x0e, 0x73, 0xfd, 0xdb, 0xa4,
	0xf1, 0xe2, 0x06, 0x16, 0xc2, 0xdd, 0x57, 0xe8, 0xee, 0x4b, 0xb2, 0x3d, 0x2d, 0x33, 0xe2, 0x65,
	0xf3, 0x9d, 0x74, 0x9c, 0x8f, 0xf5, 0xcf, 0xc5, 0xc6, 0x93, 0x31, 0xdc, 0xba, 0x34, 0x7b, 0x92,
	0x27, 0x89, 0x13, 0x3b, 0x63, 0x38, 0x9d, 0x59, 0x0b, 0x57, 0x9e, 0x69, 0x5c, 0x8c, 0x15, 0x9c,
	0x03, 0x25, 0x1c, 0x22, 0x64, 0xae, 0xd4, 0x2b, 0x50, 0xaf, 0x43, 0xbc, 0xaa, 0x5f, 0xe1, 0x14,
	0xc3, 0x00, 0x7d, 0xa8, 0x9c, 0xd9, 0x9f, 0x0c, 0xf2, 0x33, 0x84, 0x7c, 0xa8, 0x36, 0xa6, 0x40,
	0x8e, 0xec, 0x08, 0x68, 0x19, 0x87, 0xbb, 0xb0, 0x7d, 0xfd, 0x3f, 0x98, 0x4f, 0x10, 0x73, 0x55,
	0x5d, 0x99, 0x51, 0x98, 0xf2, 0x2c, 0xdb, 0x90, 0x97, 0xa3, 0xf5, 0xf7, 0x86, 0x37, 0x12, 0x00,
	0x0c, 0xef, 0x03, 0x94, 0xa2, 0x33, 0x0f, 0x79, 0x94, 0xb8, 0x5b, 0x2e, 0xcf, 0x43, 0x8d, 0xe5,
	0xa9, 0xa7, 0xdc, 0x97, 0x90, 0xe4, 0xc1, 0xec, 0xb3, 0xc7, 0xc6, 0x1b, 0x72, 0x01, 0x95, 0xf8,
	0x98, 0x42, 0xd6, 0x12, 0xdf, 0x05, 0xa7, 0x0d, 0x31, 0x33, 0x61, 0xe7, 0x38, 0xf2, 0x7c, 0x22,
	0xd9, 0x29, 0xfc, 0x4c, 0x7e, 0x6d, 0xe8, 0x64, 0x31, 0x5d, 0x3f, 0xf8, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x3a, 0xfc, 0x95, 0x68, 0xa6, 0x19, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountAPIClient is the client API for AccountAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountAPIClient interface {
	// Logins a user into their account
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Registers a new user
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	// Activates a created account
	Activate(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*ActivateResponse, error)
	// Updates user account
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Updates user private profile  account information
	UpdatePrivate(ctx context.Context, in *UpdatePrivateRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Deletes a user account
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Retrieves a user account
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Account, error)
	// Checks if an account exists
	Exist(ctx context.Context, in *ExistRequest, opts ...grpc.CallOption) (*ExistResponse, error)
	// Request to change private account
	RequestChangePrivateAccount(ctx context.Context, in *RequestChangePrivateAccountRequest, opts ...grpc.CallOption) (*RequestChangePrivateAccountResponse, error)
	// Changes the account type
	ChangeAccountType(ctx context.Context, in *ChangeAccountTypeRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Blocks an account
	BlockAccount(ctx context.Context, in *ChangeAccountRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Unblocks a blocked account
	UnBlockAccount(ctx context.Context, in *ChangeAccountRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Activates account; only admins
	AdminActivate(ctx context.Context, in *ChangeAccountRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Restores an account previously deleted
	Undelete(ctx context.Context, in *ChangeAccountRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Fetches collection of accounts
	ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*Accounts, error)
	// Searches for accounts
	SearchAccounts(ctx context.Context, in *SearchAccountsRequest, opts ...grpc.CallOption) (*Accounts, error)
}

type accountAPIClient struct {
	cc *grpc.ClientConn
}

func NewAccountAPIClient(cc *grpc.ClientConn) AccountAPIClient {
	return &accountAPIClient{cc}
}

func (c *accountAPIClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/umrs.account.AccountAPI/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/umrs.account.AccountAPI/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) Activate(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*ActivateResponse, error) {
	out := new(ActivateResponse)
	err := c.cc.Invoke(ctx, "/umrs.account.AccountAPI/Activate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/umrs.account.AccountAPI/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) UpdatePrivate(ctx context.Context, in *UpdatePrivateRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/umrs.account.AccountAPI/UpdatePrivate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/umrs.account.AccountAPI/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/umrs.account.AccountAPI/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) Exist(ctx context.Context, in *ExistRequest, opts ...grpc.CallOption) (*ExistResponse, error) {
	out := new(ExistResponse)
	err := c.cc.Invoke(ctx, "/umrs.account.AccountAPI/Exist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) RequestChangePrivateAccount(ctx context.Context, in *RequestChangePrivateAccountRequest, opts ...grpc.CallOption) (*RequestChangePrivateAccountResponse, error) {
	out := new(RequestChangePrivateAccountResponse)
	err := c.cc.Invoke(ctx, "/umrs.account.AccountAPI/RequestChangePrivateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) ChangeAccountType(ctx context.Context, in *ChangeAccountTypeRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/umrs.account.AccountAPI/ChangeAccountType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) BlockAccount(ctx context.Context, in *ChangeAccountRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/umrs.account.AccountAPI/BlockAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) UnBlockAccount(ctx context.Context, in *ChangeAccountRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/umrs.account.AccountAPI/UnBlockAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) AdminActivate(ctx context.Context, in *ChangeAccountRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/umrs.account.AccountAPI/AdminActivate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) Undelete(ctx context.Context, in *ChangeAccountRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/umrs.account.AccountAPI/Undelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*Accounts, error) {
	out := new(Accounts)
	err := c.cc.Invoke(ctx, "/umrs.account.AccountAPI/ListAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) SearchAccounts(ctx context.Context, in *SearchAccountsRequest, opts ...grpc.CallOption) (*Accounts, error) {
	out := new(Accounts)
	err := c.cc.Invoke(ctx, "/umrs.account.AccountAPI/SearchAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountAPIServer is the server API for AccountAPI service.
type AccountAPIServer interface {
	// Logins a user into their account
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// Registers a new user
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	// Activates a created account
	Activate(context.Context, *ActivateRequest) (*ActivateResponse, error)
	// Updates user account
	Update(context.Context, *UpdateRequest) (*empty.Empty, error)
	// Updates user private profile  account information
	UpdatePrivate(context.Context, *UpdatePrivateRequest) (*empty.Empty, error)
	// Deletes a user account
	Delete(context.Context, *DeleteRequest) (*empty.Empty, error)
	// Retrieves a user account
	Get(context.Context, *GetRequest) (*Account, error)
	// Checks if an account exists
	Exist(context.Context, *ExistRequest) (*ExistResponse, error)
	// Request to change private account
	RequestChangePrivateAccount(context.Context, *RequestChangePrivateAccountRequest) (*RequestChangePrivateAccountResponse, error)
	// Changes the account type
	ChangeAccountType(context.Context, *ChangeAccountTypeRequest) (*empty.Empty, error)
	// Blocks an account
	BlockAccount(context.Context, *ChangeAccountRequest) (*empty.Empty, error)
	// Unblocks a blocked account
	UnBlockAccount(context.Context, *ChangeAccountRequest) (*empty.Empty, error)
	// Activates account; only admins
	AdminActivate(context.Context, *ChangeAccountRequest) (*empty.Empty, error)
	// Restores an account previously deleted
	Undelete(context.Context, *ChangeAccountRequest) (*empty.Empty, error)
	// Fetches collection of accounts
	ListAccounts(context.Context, *ListAccountsRequest) (*Accounts, error)
	// Searches for accounts
	SearchAccounts(context.Context, *SearchAccountsRequest) (*Accounts, error)
}

func RegisterAccountAPIServer(s *grpc.Server, srv AccountAPIServer) {
	s.RegisterService(&_AccountAPI_serviceDesc, srv)
}

func _AccountAPI_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umrs.account.AccountAPI/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umrs.account.AccountAPI/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_Activate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).Activate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umrs.account.AccountAPI/Activate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).Activate(ctx, req.(*ActivateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umrs.account.AccountAPI/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_UpdatePrivate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePrivateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).UpdatePrivate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umrs.account.AccountAPI/UpdatePrivate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).UpdatePrivate(ctx, req.(*UpdatePrivateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umrs.account.AccountAPI/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umrs.account.AccountAPI/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_Exist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).Exist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umrs.account.AccountAPI/Exist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).Exist(ctx, req.(*ExistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_RequestChangePrivateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestChangePrivateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).RequestChangePrivateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umrs.account.AccountAPI/RequestChangePrivateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).RequestChangePrivateAccount(ctx, req.(*RequestChangePrivateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_ChangeAccountType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeAccountTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).ChangeAccountType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umrs.account.AccountAPI/ChangeAccountType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).ChangeAccountType(ctx, req.(*ChangeAccountTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_BlockAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).BlockAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umrs.account.AccountAPI/BlockAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).BlockAccount(ctx, req.(*ChangeAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_UnBlockAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).UnBlockAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umrs.account.AccountAPI/UnBlockAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).UnBlockAccount(ctx, req.(*ChangeAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_AdminActivate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).AdminActivate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umrs.account.AccountAPI/AdminActivate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).AdminActivate(ctx, req.(*ChangeAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_Undelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).Undelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umrs.account.AccountAPI/Undelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).Undelete(ctx, req.(*ChangeAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_ListAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umrs.account.AccountAPI/ListAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).ListAccounts(ctx, req.(*ListAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_SearchAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).SearchAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/umrs.account.AccountAPI/SearchAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).SearchAccounts(ctx, req.(*SearchAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "umrs.account.AccountAPI",
	HandlerType: (*AccountAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AccountAPI_Login_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _AccountAPI_Create_Handler,
		},
		{
			MethodName: "Activate",
			Handler:    _AccountAPI_Activate_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AccountAPI_Update_Handler,
		},
		{
			MethodName: "UpdatePrivate",
			Handler:    _AccountAPI_UpdatePrivate_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AccountAPI_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AccountAPI_Get_Handler,
		},
		{
			MethodName: "Exist",
			Handler:    _AccountAPI_Exist_Handler,
		},
		{
			MethodName: "RequestChangePrivateAccount",
			Handler:    _AccountAPI_RequestChangePrivateAccount_Handler,
		},
		{
			MethodName: "ChangeAccountType",
			Handler:    _AccountAPI_ChangeAccountType_Handler,
		},
		{
			MethodName: "BlockAccount",
			Handler:    _AccountAPI_BlockAccount_Handler,
		},
		{
			MethodName: "UnBlockAccount",
			Handler:    _AccountAPI_UnBlockAccount_Handler,
		},
		{
			MethodName: "AdminActivate",
			Handler:    _AccountAPI_AdminActivate_Handler,
		},
		{
			MethodName: "Undelete",
			Handler:    _AccountAPI_Undelete_Handler,
		},
		{
			MethodName: "ListAccounts",
			Handler:    _AccountAPI_ListAccounts_Handler,
		},
		{
			MethodName: "SearchAccounts",
			Handler:    _AccountAPI_SearchAccounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}
