apiVersion: v1
kind: Service
metadata:
  name: umrs-gateway-np
  labels:
    app: umrs
spec:
  type: NodePort
  selector:
    app: umrs-gateway
  ports:
  - port: 443
    targetPort: https
    protocol: TCP
    name: https
    nodePort: 30843
  - port: 80
    targetPort: https
    protocol: TCP
    name: http
    nodePort: 30880