apiVersion: v1
kind: Service
metadata:
  name: umrs-mysql-np
  labels:
    app: umrs
spec:
  type: NodePort
  selector:
    app: umrs-mysql
  ports:
  - port: 80
    targetPort: mysql
    protocol: TCP
    name: http
    nodePort: 30760
