serviceVersion: v1/beta
serviceName: umrs_insurance
servicePort: 7070
logging:
  level: 1
  timeFormat: 2006-01-02T15:04:05Z07:00
  disabled: true
security:
  tlsCert: /home/gideon/go/src/github.com/gidyon/umrs/certs/ledger/cert.pem
  tlsKey: /home/gideon/go/src/github.com/gidyon/umrs/certs/ledger/key.pem
  serverName: localhost
databases:
  sqlDatabase:
    required: true
    address: ec2-18-218-27-110.us-east-2.compute.amazonaws.com:30760
    host: localhost
    port: 3306
    user: root
    password: hakty11
    schema: umrs
    metadata:
      name: mysql
      dialect: mysql
      orm: gorm
  redisDatabase:
    required: false
externalServices:
- name: ledger
  type: ledger
  required: true
  address: localhost:9090
  host: localhost
  port: 9090
  tlsCert: /home/gideon/go/src/github.com/gidyon/umrs/certs/ledger/cert.pem
  serverName: localhost
- name: notification
  type: Notification
  required: true
  address: localhost:9050
  host: localhost
  port: 9050
  tlsCert: /home/gideon/go/src/github.com/gidyon/umrs/certs/ledger/cert.pem
  serverName: localhost