serviceVersion: v1/beta
serviceName: umrs_permission
servicePort: 443
logging:
  level: -1
  timeFormat: 2006-01-02T15:04:05Z07:00
  disabled: true
security:
  tlsCert: /app/secrets/keys/cert
  tlsKey: /app/secrets/keys/key
  serverName: permissions.umrs.net
databases:
  sqlDatabase:
    required: false
  redisDatabase:
    required: true
    address: umrs-redis
    host: umrs-redis
    port: 80
    metadata:
      name: redis
      useRediSearch: false
externalServices:
- name: ledger
  type: ledger
  required: true
  address: umrs-ledger:443
  host: umrs-ledger
  port: 443
  tlsCert: /app/secrets/keys/ledger/cert
  serverName: ledger.umrs.net
- name: notification
  type: Notification
  required: true
  address: umrs-notification
  host: umrs-notification
  port: 443
  tlsCert: /app/secrets/keys/notification/cert
  serverName: notifications.umrs.net
  k8service: true