serviceVersion: v1/beta
serviceName: umrs_treatment
servicePort: 443
logging:
  level: 1
  timeFormat: 2006-01-02T15:04:05Z07:00
  disabled: true
security:
  tlsCert: /app/secrets/keys/cert
  tlsKey: /app/secrets/keys/key
  serverName: treatments.umrs.net
databases:
  sqlDatabase:
    required: false
  redisDatabase:
    required: false
externalServices:
- name: ledger
  type: ledger
  required: true
  address: umrs-ledger:443
  host: umrs-ledger
  port: 443
  tlsCert: /app/secrets/keys/ledger/cert
  serverName: ledger.umrs.net
