apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "umrs-notification-hpa"
  namespace: "default"
  labels:
    app: "umrs-notification"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "umrs-notification"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
